### ISSUE TITLE
Documentation file doesn't exist

### ISSUE THREAD

**Issue by steForge** [feder-cr/linkedIn_auto_jobs_applier_with_AI#1]
The documentation file mentioned in the below section doesn't exist

Documentation
For detailed information on each component and their respective roles, please refer to the [Documentation](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/main/docs/documentation.md) file.

**Comment by feder-cr** [comment]
Hi, I'm working on this one!
