### ISSUE TITLE
image support (some jobs requests face picture)

### ISSUE THREAD

**Issue by us** [feder-cr/linkedIn_auto_jobs_applier_with_AI#10]

**Comment by feder-cr** [comment]
@us I have never had such a request, can you give me an example , with the job link?

**Comment by us** [comment]
@feder-cr https://www.linkedin.com/jobs/view/4001446789/

**Comment by feder-cr** [comment]
@us This is a non-mandatory field, does it still cause problems?

**Comment by us** [comment]
for some of them its not non mandatory!
