### ISSUE TITLE
Can I use free API like gemini api instead of openai api?

### ISSUE THREAD

**Issue by MohdTamim123** [feder-cr/linkedIn_auto_jobs_applier_with_AI#106]

**Comment by DuongVu39** [comment]
Yeah you can use any open LLM. You need to change this file [gpt.py](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/main/src/gpt.py), specifically [this line](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/main/src/gpt.py#L118) to whatever LLM framework that you want to use.

**Comment by Souheil007** [comment]
has it worked for you like that ?

**Comment by Eyalm321** [comment]
> Yeah you can use any open LLM. You need to change this file [gpt.py](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/main/src/gpt.py), specifically [this line](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/main/src/gpt.py#L118) to whatever LLM framework that you want to use.

Its not entirely accurate, there are noticable differences between ollama and chatgpt
After testing ChatOllama is having a hard time getting the parsed description, im working on it, will update

**Comment by muhammedMoussa** [comment]
> has it worked for you like that ?

I think it will require extra effort to adopt wit the model as well, or making the tool itself more flexible and offers different integration options rather than chatgpt.

**Comment by Zid428** [comment]
مرحبا هل يمكن تحويل الاداة الى قدرات اكبر واضافة سير ذاتية لتقديم اكثر للناس ؟ ومن ثم تحويلها لعمل تجاري حيث تتوفر لدي جميع التراخيص للعمل تقنيا بالسعودية

**Comment by DuongVu39** [comment]
Yes it's not a straight forward of one argument switch fixes all. I pointed out that line as the nuclear and you will still have to update other upstream downstream functions related to it as you go.
