### ISSUE TITLE
how to configure yaml file for remote jobs outside home city?

### ISSUE THREAD

**Issue by reneekharat** [feder-cr/linkedIn_auto_jobs_applier_with_AI#107]
how would I configure the file to apply to remote jobs across the USA, but in-person and hybrid ones only in the city I live in?

**Comment by pafthinder** [comment]
I suppose you have to run it separately at the moment ; or have 2 versions of config.yaml with adjusted remote and locations markups

**Comment by reneekharat** [comment]
> I suppose you have to run it separately at the moment ; or have 2 versions of config.yaml with adjusted remote and locations markups

gotcha, thank you!

**Comment by feder-cr** [comment]
@pafthinder @reneekharat join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
