### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by sidmehta04** [feder-cr/linkedIn_auto_jobs_applier_with_AI#108]
Keep getting this error
Runtime error: Error running the bot: 'model'
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by pafthinder** [comment]
somethings wrong with ur webdriver ; check if you have proper version ; you can download it here 
https://googlechromelabs.github.io/chrome-for-testing/#stable 

hope this helps

**Comment by pafthinder** [comment]
something related to gpt.py imo 
maybe ur openai_api_key is not valid in secrets.yaml?

**Comment by busedagidir** [comment]
Did you choose any model like dall-e-3?

**Comment by feder-cr** [comment]
@sidmehta04 @pafthinder @busedagidir join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
