### ISSUE TITLE
openai.RateLimitError: Error code: 429

### ISSUE THREAD

**Issue by chalde2024** [feder-cr/linkedIn_auto_jobs_applier_with_AI#109]
Afternoon ! 

Just set up everything today to give this a try and while I could not get the resume generator to work, I was able to get about ~10 submissions done before I got the below error message. 

openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-xxxxxxxxx on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}

I've set up credits and it doesn't look like it's using anything. How did you get to submit a 1000 resume as I got this to trigger after about 10 submissions only?

**Comment by josylad** [comment]
OpenAI has yet to upgrade your account. 
Add your card and wait for 10 - 24hours.
