### ISSUE TITLE
cached values

### ISSUE THREAD

**Issue by us** [feder-cr/linkedIn_auto_jobs_applier_with_AI#11]
linkedin caches most of things like phone, city etc, so we can pass directly with next when, or we can add that as optional!

**Comment by feder-cr** [comment]
yes it is possible, but from what I know the risk of being discovered d alinkeidn increases, I have something in mind anyway and I will implement it as soon as I have more time

**Comment by feder-cr** [comment]
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

@us
