### ISSUE TITLE
is it normal wait 10+ mins for job searching?

### ISSUE THREAD

**Issue by busedagidir** [feder-cr/linkedIn_auto_jobs_applier_with_AI#115]
I see this warning:

"Going to job page 1
Starting the application process for this page...
Sleeping for 895.0618209838867 seconds.."

**Comment by azjz92** [comment]
No but please do not use this until we do more trouble shooting, the bot is very risky to use right now as the repo has blown up.

**Comment by busedagidir** [comment]
Well I did use the code for one night unfortunately :(
