### ISSUE TITLE
Wrong version of Python being used

### ISSUE THREAD

**Issue by RichBOwens** [feder-cr/linkedIn_auto_jobs_applier_with_AI#116]
I'm running the bot on MacOS. 

I used Brew to install Python 3.12.5, but when loading the requirements, it keeps pointing to an earlier version (3.9.6). When trying to run the bot anyway, it's not recognizing the YAML files. Please advise on what I need to do to make sure that the right version of Python is being used to run the bot.

**Comment by RedaB2** [comment]
I have the same problem here on macOS.

**Comment by josylad** [comment]
> I'm running the bot on MacOS.
> 
> I used Brew to install Python 3.12.5, but when loading the requirements, it keeps pointing to an earlier version (3.9.6). When trying to run the bot anyway, it's not recognizing the YAML files. Please advise on what I need to do to make sure that the right version of Python is being used to run the bot.

You need to change your default Python version on your Mac. 
You can google how to do it.

**Comment by feder-cr** [comment]
@RedaB2 @RichBOwens join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
