### ISSUE TITLE
Runtime error: Error running the bot: Error parsing YAML file.

### ISSUE THREAD

**Issue by Aravind101999** [feder-cr/linkedIn_auto_jobs_applier_with_AI#117]
Runtime error: Error running the bot: Error parsing YAML file.
 showing this error

**Comment by CMaxK** [comment]
Hey @Aravind101999 - I had the same error. It was down to the formatting of the yaml file. My fix was in the plan_text_resume.yaml I had some multi-line project descriptions that the parser could not handle correctly. My fix was to just put the entire description of 1 project on 1 line. 
If I were you i'd just double check the yaml across your yaml files. Hopefully this helps a little. Maybe comparing your layout to the samples in the data_folder_example will help more

**Comment by jamesakanoa** [comment]
> Hey @Aravind101999 - I had the same error. It was down to the formatting of the yaml file. My fix was in the plan_text_resume.yaml I had some multi-line project descriptions that the parser could not handle correctly. My fix was to just put the entire description of 1 project on 1 line. If I were you i'd just double check the yaml across your yaml files. Hopefully this helps a little. Maybe comparing your layout to the samples in the data_folder_example will help more

so, if description is more than one line, it may cause parsing error?

**Comment by miltlima** [comment]
I have the same problem

**Comment by shivamt10** [comment]
I have the same issue

**Comment by eltonlaice** [comment]
I have the same issue

**Comment by kanakpandit17** [comment]
> Hey @Aravind101999 - I had the same error. It was down to the formatting of the yaml file. My fix was in the plan_text_resume.yaml I had some multi-line project descriptions that the parser could not handle correctly. My fix was to just put the entire description of 1 project on 1 line. If I were you i'd just double check the yaml across your yaml files. Hopefully this helps a little. Maybe comparing your layout to the samples in the data_folder_example will help more

No it didnt work for me.

**Comment by geekmaros** [comment]
I fixed this by leveraging on my webstorm IDE, it showed me where my yaml file had an issue as shown in my attachched screenshot, if there's an alternative plugin like that for VS code, it should fix it

<img width="1510" alt="Screenshot 2024-09-03 at 01 10 34" src="https://github.com/user-attachments/assets/c21c0210-7af7-4f2f-af41-7f22dca79ffe">

**Comment by geekmaros** [comment]
> @geekmaros @miltlima join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

Oh yeah sure would loved to
