### ISSUE TITLE
AIHawk Sleeping for 896 seconds

### ISSUE THREAD

**Issue by gymmyck** [feder-cr/linkedIn_auto_jobs_applier_with_AI#119]
I think I've proceeded correctly with all the steps but when running the bot the terminal gets stuck here:

Starting Chrome browser to log in to LinkedIn.
Navigating to the LinkedIn login page...
Security check not completed. Please try again later.
Starting the search for Intern Frontend Developer in United Kingdom.
Going to job page 0
Starting the application process for this page...
Sleeping for 896.5919418334961 seconds.

Also, how much credit do we need to add on the Open AI Account? Would it need a monthly subscription?

Thanks!

**Comment by busedagidir** [comment]
I had the same waiting response. Then it goes to another page and does the same things.
I am using chatgpt free, no payment and I didnt face with any problem about money so far.

**Comment by KaluArunsi** [comment]
Yes but the problem now is it isn't actually applying for anything exactly because no mails are coming in., confirming the application.

**Comment by pafthinder** [comment]
you can change it in start_applying method of LinkedInJobManager class ; it won't help though, cause, as the @KaluArunsi mentioned - currently bot doesn't apply (at least for me, but I assume it does not for everyone, cause my LI is not special...)

I described my issue here 
https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/114 

If you have any ideas how to fix - all of them are appreciated!

**Comment by gymmyck** [comment]
Indeed, I was waiting for it, and I noticed it was going through some sort of application process per LinkedIn Jobs Page. But after that if you go check the My jobs -> Applied section on LinkedIn there are no jobs applied to (other than the ones we manually applied to).

As @KaluArunsi said, there is no confirmation mails coming in.

**Comment by pafthinder** [comment]
I have LinkedIn learning subscription, maybe that changes whole layout of LI page and therefore markups are misaligned? 
@gymmyck ; @KaluArunsi  ; @busedagidir - do you have LI premium or LI learning subscription guys?

**Comment by gymmyck** [comment]
@pafthinder I've got LI premium. What do you mean by markups are misaligned?

**Comment by pafthinder** [comment]
I have LI learning. But that's not necessarily the case, because some people for whom script doesn't work are regular LI users.

https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/114 - check this one to see the explanation. It's all about pointing to the proper elements of site, so script has data to proceed with application process. If Selenium doesn't catch data (because it points to wrong/empty HTML elements), rest of the script fails miserably.
