### ISSUE TITLE
in cover letter section, always write that! 

### ISSUE THREAD

**Issue by us** [feder-cr/linkedIn_auto_jobs_applier_with_AI#12]
I'm sorry, but I cannot provide a cover letter based on the personal information provided.

**Comment by feder-cr** [comment]
Ok, I will fix tomorrow, thanks

**Comment by feder-cr** [comment]
@us can you link me of a job where this bug occurs so I can debbuging

**Comment by us** [comment]
https://www.linkedin.com/jobs/view/3993713563/
<img width="758" alt="Screenshot 2024-08-12 at 18 27 36" src="https://github.com/user-attachments/assets/912134d6-d714-4601-998e-1b4f42ebda85">

**Comment by feder-cr** [comment]
@us  the bug should be fixed, please check and let me know


If you’re interested, I’d like to invite you to join our AIHack Telegram community. It’s a fantastic space where you can:

- Get answers to your questions
- Propose new ideas
- Exchange tips and advice with other users of our software

🌟 Join our community here -> [AIHack Telegram Community](https://t.me/AIhawkCommunity)
