### ISSUE TITLE
YAML file parsing error

### ISSUE THREAD

**Issue by jamesakanoa** [feder-cr/linkedIn_auto_jobs_applier_with_AI#120]
Runtime error: Error running the bot: Error parsing YAML file

**Comment by soykot2910** [comment]
> Runtime error: Error running the bot: Error parsing YAML file

same issue

**Comment by ManojSharmaK** [comment]
rebuild the plain_text_resume.yaml file again 
it fixed my issue by redoing it with line by line edits

**Comment by KaluArunsi** [comment]
run it through the AI if you use cursor with this prompt: 

> review this yaml file thoroughly line by line and spot errors

**Comment by jamesakanoa** [comment]
I checked for lint errors as well. The example file syntax may not be consistent with production file others have found success with. I used https://www.yamllint.com/ to check lint errors.

**Comment by jamesakanoa** [comment]
after line by line rewrite efforts, I'm getting this error.

Runtime error: Error running the bot: AttributeError in education_details processing: AttributeError in Education: 'str' object has no attribute 'items'

For context, I do not plan on listing out all the grad school courses here.

**Comment by KaluArunsi** [comment]
actually the readme provides a fairly decent example for this, if you want to list them all then they must all be indented

**Comment by jamesakanoa** [comment]
> actually the readme provides a fairly decent example for this, if you want to list them all then they must all be indented

True but I have no intentions to list out the courses and would rather leave it blank.

**Comment by jamesakanoa** [comment]
<img width="623" alt="Screenshot 2024-08-29 at 11 09 34 AM" src="https://github.com/user-attachments/assets/daadb931-8d7a-462d-8c3c-f8c6718b1bfd">
as you can see from screenshot.. it reads to be syntax error but lint errors were not found.
so I am confused? thanks for your assistance with this.

**Comment by KaluArunsi** [comment]
there isn't any problem here from what i can see, i doubt the error is from this file, check your plain-resume.yaml file

**Comment by jamesakanoa** [comment]
> there isn't any problem here from what i can see, i doubt the error is from this file, check your plain-resume.yaml file

thank you, will do!

**Comment by jamesakanoa** [comment]
well this is embarrassing.. i had not installed requirements lol

pip install -r requirements.txt

**Comment by feder-cr** [comment]
@jamesakanoa @KaluArunsi @ManojSharmaK @soykot2910 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
