### ISSUE TITLE
Can we add current CV parser and fill resume config automatically?

### ISSUE THREAD

**Issue by pakistanimoon** [feder-cr/linkedIn_auto_jobs_applier_with_AI#124]
I wish i had an option to upload my current resume, which automatically get parsed and as many fields as possible in "plain_text_resume.yaml" should be populated automatically.

**Comment by JeanMILPIED** [comment]
you can try https://raizuum.onrender.com/

**Comment by keezysilencer** [comment]
@pakistanimoon 
1. Upload your CV to chatGPT. 
2. Use the prompt: `Using the resume uploaded. Extract the info into a yaml file following the template below: `
3. Paste the`plain_text_resume.yaml` file below.

**Comment by feder-cr** [comment]
@keezysilencer @pakistanimoon join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
