### ISSUE TITLE
Invalid type for key 'remote' in config file data_folder/config.yaml. Expected <class 'bool'>.

### ISSUE THREAD

**Issue by Aravind101999** [feder-cr/linkedIn_auto_jobs_applier_with_AI#126]
Invalid type for key 'remote' in config file data_folder/config.yaml. Expected <class 'bool'>.   how to solve this

**Comment by Mahmoud-Sh3ban** [comment]
Replace [true/false] with just true or false to fix it.

**Comment by Aravind101999** [comment]
I did that bro. Only true words used

**Comment by KaluArunsi** [comment]
do not use sentence case for the bool.
use `true` or `false` not `True` or `False`

**Comment by PtJayMishra** [comment]
> do not use sentence case for the bool. use `true` or `false` not `True` or `False`
used 'true' still facing same issue

**Comment by Aravind101999** [comment]
> do not use sentence case for the bool. use `true` or `false` not `True` or `False`

Runtime error: Error running the bot: Error parsing YAML file.  after i solved above . now showing this

**Comment by feder-cr** [comment]
Guys, please follow the readme!
