### ISSUE TITLE
Multi lingual

### ISSUE THREAD

**Issue by MaraScott** [feder-cr/linkedIn_auto_jobs_applier_with_AI#127]
Hi,

how can I make this multi lingual to request the bot to read text in french (right now the title moderator do not work) and to generate resume in french too ?

if you point me where in the code, I might be able to participate in the evolution

**Comment by feder-cr** [comment]
@MaraScott not for now.
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
