### ISSUE TITLE
Support JSONResume for resume pdf generation 

### ISSUE THREAD

**Issue by barakplasma** [feder-cr/linkedIn_auto_jobs_applier_with_AI#128]
There's an existing standard for plain text resumes. If your project would use JSONResume instead of your own format, a job seeker could use the same file to generate a pdf or website of their resume in addition to using your tool

https://github.com/jsonresume/resume-schema

**Comment by feder-cr** [comment]
@barakplasma  https://github.com/feder-cr/resume_render_from_job_description
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
