### ISSUE TITLE
How to get confirmation which jobs are applied?

### ISSUE THREAD

**Issue by djfreex** [feder-cr/linkedIn_auto_jobs_applier_with_AI#13]
Great work and idea. Looking forward to following the progress.

It doesnt look like applied jobs are showing up under My Jobs>Applied. How does one know which jobs were applied?

**Comment by feder-cr** [comment]
There is definitely a sixzone of linekidn that allows you to see the jobs you applied for, plus inside the data_folder/output folder should have the logs and work pretty well.

@djfreex if your doubts persist enter the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
