### ISSUE TITLE
Make Resume data Optional

### ISSUE THREAD

**Issue by warpapaya** [feder-cr/linkedIn_auto_jobs_applier_with_AI#134]
What work would be needed to make items in the resume data optional. There are use cases where education, projects, links to external items etc. are either not applicable or not available.

For example, I have no university degree or university experience. Current state if I fill the resume with "none" or "N/A" values, the AI will invent details to put in that place.

Example of current education details:
`education_details:
  - degree: "None"
    university: "None"
    gpa: "none"
    graduation_year: "none"
    field_of_study: "none"`

Example of project without a link:
`projects:
  - name: "Maeve Home AI Model"
    description: "M.A.E.V.E. - Multifunctional Autonomous Entity for Virtual Engagement, is an AI model built on local hardware using multiple open source models to create an interface point for my family to interact with our smart home and its assets."
    link: "none"`

**Comment by jamesakanoa** [comment]
https://www.youtube.com/watch?v=gdW9wogHEUM 17:10ish.. may help

**Comment by feder-cr** [comment]
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by warpapaya** [comment]
Thanks for this!
