### ISSUE TITLE
Adding more options available other than GPT

### ISSUE THREAD

**Issue by 0xrsydn** [feder-cr/linkedIn_auto_jobs_applier_with_AI#14]
I would like to use groq or maybe claude as GPT alternative (well i dont have any api key credits) tho. Will those options available later? Thanks

**Comment by ralyodio** [comment]
would be nice to use ollama.com api for open models

**Comment by feder-cr** [comment]
it can be done very well, and it is also quite simple to implement given the design, but how would you want the choice to happen?

through the main?

join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

@ralyodio @0xrsydn
