### ISSUE TITLE
lib_resume_builder_AIHawk?

### ISSUE THREAD

**Issue by peter-lyons-2024** [feder-cr/linkedIn_auto_jobs_applier_with_AI#140]
lib_resume_builder_AIHawk supposed to be a local Python file or module within project?

**Comment by feder-cr** [comment]
@peter-lyons-2024 https://github.com/feder-cr/lib_resume_builder_AIHawk

join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
