### ISSUE TITLE
Attribute error in experience details

### ISSUE THREAD

**Issue by slippyswag** [feder-cr/linkedIn_auto_jobs_applier_with_AI#143]
I'm trying to run the bot, but it keeps returning the same error message.

Runtime error: Error running the bot: AttributeError in experience_details processing: AttributeError in Experience: 'str' object has no attribute 'values'
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

I have used a YAML validator which confirms my formatting is correct, and I made sure not to exclude any items in the template. The only thing I added was one additional line in each key_responsibilities for three positions.

I am using windows with command prompt.

Any ideas?

**Comment by Andres-Ventura** [comment]
look at the key references amigo

**Comment by Andres-Ventura** [comment]
key_responsibilities:
      - responsibility_1:

**Comment by slippyswag** [comment]
I am not worthy... Thank you

@Andres-Ventura

**Comment by Andres-Ventura** [comment]
lol
