### ISSUE TITLE
OpenAI Rate Limit Question

### ISSUE THREAD

**Issue by santockz** [feder-cr/linkedIn_auto_jobs_applier_with_AI#145]
I keep getting 

`openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization <org> on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}`

even though I have purchased openAi credits and have saved my payment card there. Anyone know how do I get passed this? Thank you.

**Comment by MrKangs** [comment]
I am also getting the same error as well

**Comment by josylad** [comment]
You need to wait for 12 hours for OpenAI to upgrade your account.

**Comment by sameelshahid** [comment]
i only got 3 RPM

**Comment by michaelsam94** [comment]
how much credit do I need for applying for example 500 jobs
