### ISSUE TITLE
Caching Questions and answers

### ISSUE THREAD

**Issue by yash1744** [feder-cr/linkedIn_auto_jobs_applier_with_AI#149]
Many questions in the easy apply process tend to be repetitive or similar, like "How many years of experience do you have in a particular language?" or "What is your mobile number?". Could we create a lookup interface using a text file to handle these common questions? This way, the system could provide answers instantly without needing to prompt GPT, saving on API queries.

**Comment by josylad** [comment]
This sounds like a good idea, can you work on this and make a PR?

**Comment by chiggly007** [comment]
this is a great use case for GPTCache or something similar

**Comment by feder-cr** [comment]
@yash1744  @josylad  we alredy do this.
@chiggly007 what is this? join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
