### ISSUE TITLE
Scripts Discards instead of clicking next while submitting application

### ISSUE THREAD

**Issue by nishit2003** [feder-cr/linkedIn_auto_jobs_applier_with_AI#150]
<img width="1101" alt="Screenshot 2024-08-29 at 11 30 02 PM" src="https://github.com/user-attachments/assets/13824d12-4e80-40ec-95c1-34061d81485b">

when running the script, for some reason it discards the application after filling in the personal detail page.

**Comment by feder-cr** [comment]
@nishit2003 any update?

**Comment by feder-cr** [comment]
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by naganikshith04** [comment]
Did it get solved for you?

**Comment by nishit2003** [comment]
nope, still facing the same issue

**Comment by naganikshith04** [comment]
I got this mail from ChatGPT, I tried hitting the GPT API and was getting same error. Is it same with you guys?
<img width="457" alt="image" src="https://github.com/user-attachments/assets/0babafdd-48f6-4060-bffc-77eb3c3f2a16">

**Comment by nishit2003** [comment]
I dont think these are related issues

**Comment by nishit2003** [comment]
Its fixed, if you pull in the new changes

**Comment by feder-cr** [comment]
@naganikshith04 @nishit2003 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
