### ISSUE TITLE
charmap codec error

### ISSUE THREAD

**Issue by sunnydigital** [feder-cr/linkedIn_auto_jobs_applier_with_AI#151]
>Runtime error: Error running the bot: 'charmap' codec can't decode byte 0x9d in position 4573: character maps to undefined
>Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by diegohd8** [comment]
How did you solve it??

**Comment by sunnydigital** [comment]
I was using wrong chracters in my resume YAML file. I just copied the yaml file into chatgpt and asked it to find specifically where there might be encoding errors
