### ISSUE TITLE
unable to add website or portfolio 

### ISSUE THREAD

**Issue by Pro2004-a11** [feder-cr/linkedIn_auto_jobs_applier_with_AI#154]
Is there a way to add  website or portfolio links?

**Comment by Suhas-S19** [comment]
You need to change requirements as per your eligibility in "plain_text_resume.yaml" available in data_folder!  Thanks!

**Comment by Pro2004-a11** [comment]
thank you
how I need to do it? 
If I just add under 'personal_informaion' I have an error

**Comment by feder-cr** [comment]
ok, i will fix @Pro2004-a11 @Suhas-S19
