### ISSUE TITLE
Support for Offline Operation and Custom LLaMA Integration

### ISSUE THREAD

**Issue by MoezBouchoucha** [feder-cr/linkedIn_auto_jobs_applier_with_AI#157]
Hi,I am exploring the possibility of using this code in an environment where API access is not available. Specifically, I would like to know:

- Offline Operation: Can the code function without an external API, such as OpenAI's API? If so, what modifications or configurations are required to enable this?
- Custom LLaMA Integration: Is it possible to replace the OpenAI API with a locally hosted LLaMA model? If yes, could you provide guidance on how to set up and configure the code to work with a LLaMA model hosted on my own computer?
- use gemini free api with the corresponding waiting time

**Comment by earl562** [comment]
Hey @MoezBouchoucha,

in short YES, Ollama integrations will be made to the repo.

**Vision**

To make the barrier to entry with using the bot as low as possible, this means keeping cost low(Ollama integrations) and Non technical user friendly

**Comment by earl562** [comment]
Issue is being handled by another contributor
