### ISSUE TITLE
ChatGPT autofill reuses the same "summery" for new open job positions

### ISSUE THREAD

**Issue by Antharithm** [feder-cr/linkedIn_auto_jobs_applier_with_AI#158]
I have noticed that ChatGPT's generated autofill reuses the same "summery" or "job title" and "Cover Letter" for unrelated open job positions. Sometimes it uses the previous job title for another application. For example: I apply to a job called Software dev at a company called "SoftwareTech" then i apply to another job from a company called "Hardware Tech" - The autofill will use "SoftwareTech" in the summary to the HardwareTech job application. 

It should use the title of the job you are applying to and not reuse a previous job title or company

**Comment by xyanglu** [comment]
I encountered this bug as well.

**Comment by feder-cr** [comment]
@Antharithm i fixed this fro cover letter, please let me know another example with linkeidn job link!
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by xyanglu** [comment]
I used the latest code from `main` and still sent the wrong cover letter to this link https://channel-factory.workable.com/jobs/3770198

**Comment by feder-cr** [comment]
@xyanglu join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by feder-cr** [comment]
@xyanglu any update?

**Comment by xyanglu** [comment]
Summary is stating the wrong position + company name but cover letter is stating the correct one.
