### ISSUE TITLE
won't parse config.yaml file

### ISSUE THREAD

**Issue by ctbritt** [feder-cr/linkedIn_auto_jobs_applier_with_AI#159]
Have tried with my own information as well as the sample file. Will not parse the config.yaml file. No detailed error message, just 
```
Runtime error: Error running the bot: Error parsing YAML file.
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration
```

**Comment by Antharithm** [comment]
You have to check all of the values in the config file. Check all bools are valid and quotes are closed etc. I had this error but double checked that file and made a few changes until it finally worked

**Comment by ctbritt** [comment]
Error. seems to be an issue with my cv
