### ISSUE TITLE
How likely to be banned when using this tool?

### ISSUE THREAD

**Issue by feslima** [feder-cr/linkedIn_auto_jobs_applier_with_AI#16]
First off, amazing job automating such tedious task!

I know there is a disclaimer, but I would like to know: is there any risk of being banned by linkedin? If so, has anyone faced any issues?

Thanks!

**Comment by LozmindaSnr** [comment]
We can't DM on GH, so forgive me using an issue to post. 
a) I concur with @feslima, I've skimmed the code, looks fantastic, bravo !
b) I again concur @feslima at some point linkdIn is going to wise up, (or perhaps not), I guess it boils down to their T&Cs/CoC.  [This SO post is quite old so am guessing things have moved on ?](https://stackoverflow.com/questions/7152579/detect-if-user-is-human-without-captcha-or-useragent)

**Comment by feder-cr** [comment]
@LozmindaSnr @feslima @Jheesbrough 

the bot simulates human activity, the risk is very low, I don't know anyone who has ever been banned, obviously the risk exists

If you’re interested, I’d like to invite you to join our AIHack Telegram community. It’s a fantastic space where you can:

- Get answers to your questions
- Propose new ideas
- Exchange tips and advice with other users of our software

🌟 Join our community here -> [AIHack Telegram Community](https://t.me/AIhawkCommunity)
