### ISSUE TITLE
Access to your LinkedIn account has been temporarily restricted

### ISSUE THREAD

**Issue by slippyswag** [feder-cr/linkedIn_auto_jobs_applier_with_AI#160]
I'm using a burner LinkedIn for testing, and got this warning within 12 hours:

**Access to your account has been temporarily restricted**
Why did this happen?
We take proactive actions to protect you when we detect potential unauthorized access or other activity that doesn’t comply with our policies.

**What can I do next?**
We first need to verify your identity to ensure your account safety. To regain access to your account, please submit a government-issued ID.

I can verify my account with my ID but I don't want to risk my actual account getting banned.

I've done a lot of logins / logouts and have zero connections on this test profile, but I'm curious if anyone else is having the same issue or concern. 

Otherwise, would love to know best practices to prevent LinkedIn from flagging my account. I'm sure one obvious suggestion is not logging in and out so many times in one day... 

And would also love to know if people are using this on their actual LinkedIn's, for how long, and how that's working.

**Comment by feder-cr** [comment]
The bot was created for educational purposes, we take no responsibility for how it is used!
