### ISSUE TITLE
i don't solve this error, can you help?

### ISSUE THREAD

**Issue by emirhanai** [feder-cr/linkedIn_auto_jobs_applier_with_AI#161]
![image](https://github.com/user-attachments/assets/8f9eee44-d85e-4b13-a354-7b4522fbe0f3)

i don't solve this error, can you help?

**Comment by Antharithm** [comment]
Just choose the first style

**Comment by Antharithm** [comment]
dont write anything just choose the first option

**Comment by emirhanai** [comment]
I use Google colab. I don't choice, only write. I guess I wrote 1, don't works.

**Comment by azjz92** [comment]
Hit the enter key

**Comment by emirhanai** [comment]
Doesn't work while I press enter.

**Comment by emirhanai** [comment]
723;1H8
[?] Which style would you like to adopt?: 
 > Modern (style author -> https://github.com/blaketylerfullerton)
   Default (style author -> https://github.com/krishnavalliappan)
   Create your resume style in CSS

HRuntime error: Error running the bot: Failed to initialize browser: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x57b4bbacb4e3 <unknown>
#1 0x57b4bb7fac76 <unknown>
#2 0x57b4bb821757 <unknown>
#3 0x57b4bb820029 <unknown>
#4 0x57b4bb85eccc <unknown>
#5 0x57b4bb85e47f <unknown>
#6 0x57b4bb855de3 <unknown>
#7 0x57b4bb82b2dd <unknown>
#8 0x57b4bb82c34e <unknown>
#9 0x57b4bba8b3e4 <unknown>
#10 0x57b4bba8f3d7 <unknown>
#11 0x57b4bba99b20 <unknown>
#12 0x57b4bba90023 <unknown>
#13 0x57b4bba5e1aa <unknown>
#14 0x57b4bbab46b8 <unknown>
#15 0x57b4bbab4847 <unknown>
#16 0x57b4bbac4243 <unknown>
#17 0x7f80f084eac3 <unknown>

Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by Younes43** [comment]
> �723;1H�8 [?] Which style would you like to adopt?:
> 
> > Modern (style author -> https://github.com/blaketylerfullerton)
> > Default (style author -> https://github.com/krishnavalliappan)
> > Create your resume style in CSS
> 
> HRuntime error: Error running the bot: Failed to initialize browser: Message: unknown error: cannot find Chrome binary Stacktrace: #0 0x57b4bbacb4e3 #1 0x57b4bb7fac76 #2 0x57b4bb821757 #3 0x57b4bb820029 #4 0x57b4bb85eccc #5 0x57b4bb85e47f #6 0x57b4bb855de3 #7 0x57b4bb82b2dd #8 0x57b4bb82c34e #9 0x57b4bba8b3e4 #10 0x57b4bba8f3d7 #11 0x57b4bba99b20 #12 0x57b4bba90023 #13 0x57b4bba5e1aa #14 0x57b4bbab46b8 #15 0x57b4bbab4847 #16 0x57b4bbac4243 #17 0x7f80f084eac3
> 
> Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

You probably don't have chrome installed, you can install it using:

sudo apt update && sudo apt -y upgrade && sudo apt -y autoremove
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt -y install ./google-chrome-stable_current_amd64.deb
