### ISSUE TITLE
Use chtgpt or smth else to parse existing cv and fill plain_text_resume.yaml

### ISSUE THREAD

**Issue by air55555** [feder-cr/linkedIn_auto_jobs_applier_with_AI#163]
Make prompt or smth to use chtgpt or smth else to parse existing cv and fill plain_text_resume.yaml. Automate yaml creating

**Comment by muhd360** [comment]
ill like to be assigned this issue

**Comment by josylad** [comment]
This can be trickish. LLMs are not always 100% accurate, human involvement is highly recommended.

**Comment by air55555** [comment]
merged to https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/pull/204
