### ISSUE TITLE
name of generated CV shall be customized [feature proposal] 

### ISSUE THREAD

**Issue by pafthinder** [feder-cr/linkedIn_auto_jobs_applier_with_AI#165]
@ linkedIn_easy_applier
`file_path_pdf = os.path.join(folder_path, f"CV_{random.randint(0, 9999)}.pdf") `

this should include at least name of the company imo 
I'd prefer to also hardcode my name to the name 
so 
"CV_myname_{company_name}.pdf"

**Comment by pafthinder** [comment]
it can be something like that imo 

```
def _create_and_upload_resume(self, element, job):
        folder_path = 'generated_cv'
        os.makedirs(folder_path, exist_ok=True)
        try:
            company_name = job.company.replace(' ', '_')[:30]  # Limit company name to 30 characters
            file_name = f"CV_yournamehardcoded_{company_name}.pdf"
            file_path_pdf = os.path.join(folder_path, file_name)
            with open(file_path_pdf, "xb") as f:
                f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
            element.send_keys(os.path.abspath(file_path_pdf))
            job.pdf_path = os.path.abspath(file_path_pdf)
            time.sleep(2)
        except Exception:
            tb_str = traceback.format_exc()
            raise Exception(f"Upload failed: \nTraceback:\n{tb_str}")
```

can create PR if approved 
@feder-cr

**Comment by feder-cr** [comment]
@pafthinder Companies often use non-standard characters or special symbols in their names. This can lead to compatibility issues when these names are used for filenames, as many filesystems or software applications do not support special characters in file names. As a result, errors may occur in file management, sharing, or interoperability between different systems.

**Comment by pafthinder** [comment]
I see. 

CV_5450 looks suspicious af though :(
