### ISSUE TITLE
Code running and browsing the jobs, however it is not applying. 

### ISSUE THREAD

**Issue by zeelbhatt** [feder-cr/linkedIn_auto_jobs_applier_with_AI#171]
The code starts to run, it applied the filters. but is not sending the application to any job.

**Comment by 50sotero** [comment]
same thing happens to me

**Comment by npunith1neu** [comment]
Facing the same issue.

**Comment by arspesk** [comment]
same

**Comment by Aayushist** [comment]
Same. Any idea? How to resolve. It goes through every page. Clicks on easy Apply and then returns back.

**Comment by zeelbhatt** [comment]
can you guys ask it on the Telegram community ? 
https://t.me/AIhawkCommunity

**Comment by ralyodio** [comment]
how long did you wait? it simulates a human reading the job description and company page.

**Comment by npunith1neu** [comment]
Around 45 minutes to an hour.

**Comment by ralyodio** [comment]
```
Starting the search for Frontend Engineer in United States.
Going to job page 0
Starting the application process for this page...
Applying to jobs on this page has been completed!
Sleeping for 801.4321193695068 seconds.
```

you should see something like this

**Comment by npunith1neu** [comment]
<img width="729" alt="image" src="https://github.com/user-attachments/assets/e246990c-862b-433a-bc2e-2fade0819024">

**Comment by ralyodio** [comment]
its sleeping for 800 seconds -- that's like 9 minutes. just let it run.

**Comment by ralyodio** [comment]
@feder-cr you can close this. its just user error.

**Comment by arspesk** [comment]
@ralyodio man you don't get it, it doesn't apply at all, it doesn't click "easy applying" button, doesn't open modal for applying. All it does it just logs in console that it starts the application process, scrolls 1st page down and up, and than times out for 9 min. Thats it. Waiting 9 also doesn't help, it does the same thing again. Even the log you provided doesn't say that it has applied to any of the jobs

**Comment by ralyodio** [comment]
i don't know it works for me.

**Comment by npunith1neu** [comment]
@ralyodio  What's your python version?

**Comment by ralyodio** [comment]
are there jobs on the page?

**Comment by npunith1neu** [comment]
> are there jobs on the page?

Yes

**Comment by ralyodio** [comment]
> @ralyodio What's your python version?

3.10

**Comment by ralyodio** [comment]
> > are there jobs on the page?
> 
> Yes

ok, not sure maybe open up your criteria a bit

**Comment by npunith1neu** [comment]
> i don't know it works for me.

Are you getting emails from linkedin as the confirmation email for submission?

**Comment by arspesk** [comment]
Surprising enough, but simply reinstalling chrome helped me

**Comment by npunith1neu** [comment]
Which version of Chrome are you using now?

**Comment by arspesk** [comment]
128.0.6613.114

**Comment by arspesk** [comment]
Nvm, worked once, and stopped working again after restart lol, still goes into sleep indefinitely…

**Comment by aarizpe10** [comment]
Having this same issue, left it open for almost 2 hours. Came back and saw 0 jobs it applied for, but said it had no more jobs to apply to and went to sleep.

**Comment by feder-cr** [comment]
reinstall all, and follow readme!

**Comment by feder-cr** [comment]
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by bakshiabhi** [comment]
same issue,
have latest chrome, tried multiple installs 
it just goes to sleep mode and dost not apply any jobs , it filter on linked jobs and then stops at easy apply.
On telegram same Question from some 1 has no resolution. Please can u help to address it? thanks
