### ISSUE TITLE
User feedback and feature requests

### ISSUE THREAD

**Issue by parth-savjani** [feder-cr/linkedIn_auto_jobs_applier_with_AI#172]
1. Adding detailed rules at the top of each section in config.yaml and plain_text_resume.yaml file
    - Required or Optional
    - Impact of the values being entered
    - Best practice or default value

2. Avoid using GPT for questions based on personal information like first name, last name, phone number, email, etc. instead use the config file directly based on string matching, if possible. It will save unnecessary API calls.

3. Limiting GPT calls based on rate limits if it is available in response. Otherwise based on usage tiers to avoid hitting rate limit reached errors from OpenAI

**Comment by feder-cr** [comment]
@parth-savjani join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
