### ISSUE TITLE
Rate Limit & Previous Companies

### ISSUE THREAD

**Issue by vlance11** [feder-cr/linkedIn_auto_jobs_applier_with_AI#175]
LinkedIn just implement a limit on how many jobs one can apply to in a 24 hour window, we need to be able to monitor this and stay under the limit.  Also companies should be added to the do not apply again until cleared, otherwise it can apply to the same company 10-20x's in a run.

**Comment by air55555** [comment]
Hmm interesting, do you have a LinkedIn doc about that?
