### ISSUE TITLE
Enhancement: Use webdriver manager to remove the requirement to download chrome

### ISSUE THREAD

**Issue by Jheesbrough** [feder-cr/linkedIn_auto_jobs_applier_with_AI#18]
https://pypi.org/project/webdriver-manager/

The package is still being maintained, just not updated with new features, if this is something that is agreeable I'll make a PR for it.

**Comment by feder-cr** [comment]
We already use this:

join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
