### ISSUE TITLE
Error running the bot: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by ayushiimishra** [feder-cr/linkedIn_auto_jobs_applier_with_AI#182]
what to do now? this error keeps popping up Error running the bot: 'str' object has no attribute 'items'
Please help

**Comment by talibilat** [comment]
Use "Data folder" instead of "Data folder example". It should solve the problem.

**Comment by feder-cr** [comment]
@talibilat @ayushiimishra any update? join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
