### ISSUE TITLE
yaml parse issue

### ISSUE THREAD

**Issue by jitendramasai** [feder-cr/linkedIn_auto_jobs_applier_with_AI#188]
Hello i have cloned this to my local and tried to run but facing below error

Runtime error: Error running the bot: Error parsing YAML file.

**Comment by kanakpandit17** [comment]
Same

**Comment by akashthele** [comment]
getting same eerror any resoluton.@kanakpandit do we have to edit plain_text_resume.yaml  to  plaintext_resume.yaml  from daa_folder

**Comment by air55555** [comment]
Just read v3 branch readme troubleshooting section

**Comment by ralyodio** [comment]
are the v3 planned features tracked somewhere?

**Comment by geekmaros** [comment]
I fixed this by leveraging on my webstorm IDE, it showed me where my yaml file had an issue as shown in my attachched screenshot, if there's an alternative plugin like that for VS code, it should fix it

<img width="1510" alt="Screenshot 2024-09-03 at 01 10 34" src="https://github.com/user-attachments/assets/c21c0210-7af7-4f2f-af41-7f22dca79ffe">

**Comment by air55555** [comment]
> I fixed this by leveraging on my webstorm IDE, it showed me where my yaml file had an issue as shown in my attachched screenshot, if there's an alternative plugin like that for VS code, it should fix it
> 
> <img alt="Screenshot 2024-09-03 at 01 10 34" width="1510" src="https://private-user-images.githubusercontent.com/20782479/363805335-c21c0210-7af7-4f2f-af41-7f22dca79ffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzc0NDMsIm5iZiI6MTcyNTMzNzE0MywicGF0aCI6Ii8yMDc4MjQ3OS8zNjM4MDUzMzUtYzIxYzAyMTAtN2FmNy00ZjJmLWFmNDEtN2YyMmRjYTc5ZmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA0MTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjRlYTMyOGVkNzUzMmRlYjM0NzBmNzg3MzIwMGQ4ODJiMGYxODQ3NGVkYTczZGJmM2M0MDZkYWY1OTIzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fBDIvmwXuvtKSrp29WwioZ5mM3fyWZ642-iqTX9lTMY">

@geekmaros could you please verify your bad yaml using the verifier from project redmi?

**Comment by akbhatisain** [comment]
Hi,
I have tried the main branch and the v3 branch both.
I have tried the following:-
(virtual) MacBook-Air-2 linkedIn_auto_jobs_applier_with_AI % python3.11 main.py
(virtual) MacBook-Air-2 linkedIn_auto_jobs_applier_with_AI % python main.py
(virtual) MacBook-Air-2 linkedIn_auto_jobs_applier_with_AI % python3.11 main.py --resume ./data_folder/plain_text_resume.yaml

All are giving me the same error :
Runtime error: Error running the bot: Error parsing YAML file.
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

I am using MacBook m1 series, python multiple version installed but I have set the default version as Python 3.11.
Any help @feder-cr @earl562 @azjz92

Thanks
