### ISSUE TITLE
GPTAnswerer

### ISSUE THREAD

**Issue by axtownsend** [feder-cr/linkedIn_auto_jobs_applier_with_AI#19]
Hi Mario,
Great app.
I'm getting an error on the main.py file related to the GPTAnswerer call from gpt.py.
'**************************************
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from gpt import GPTAnswerer
  File "/home/allen/Documents/AIHawk/LinkedIn_AIHawk_automatic_job_application/gpt.py", line 114, in <module>
    class GPTAnswerer:
  File "/home/allen/Documents/AIHawk/LinkedIn_AIHawk_automatic_job_application/gpt.py", line 128, in GPTAnswerer
    def find_best_match(text: str, options: list[str]) -> str:
TypeError: 'type' object is not subscriptable
'****************************************
I checked the other issues and didn't see anything seemingly related.
Thanks,
Allen Townsend

**Comment by axtownsend** [comment]
I determined the error was a 3.8 vs. 3.9 issue fixed by updating the gpt.py file row 128.
changes code to:
def find_best_match(text: str, options: ****List**[**str]) -> str:
and adding import
from typing import Dict, List
Thanks,
Allen Townsend

**Comment by feder-cr** [comment]
Hi, so this software not work with python 3.8?

@axtownsend  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by feder-cr** [comment]
Hi, so this software not work with python 3.8?

@axtownsend  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by feder-cr** [comment]
Hi, so this software not work with python 3.8?

@axtownsend  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by Josde** [comment]
In case you are interested in updating this (although this is minor) [https://peps.python.org/pep-0585/](PEP 585) recommends using `list[str]` rather than `typing.List[str]`, and even says that that part of the typing module may get deprecated in the future. Although the first syntax I used is only supported in 3.9+, you can do `from __future__ import annotations` at the top of files to make it work in any version of Python 3.7+.

**Comment by axtownsend** [comment]
Thanks Fredrico I will try that.
