### ISSUE TITLE
New Feature. LLAMA local model  integration. Also investigate on free LLAMA api endpoints .

### ISSUE THREAD

**Issue by air55555** [feder-cr/linkedIn_auto_jobs_applier_with_AI#190]
Integrate llama instead of OpenAI api.

**Comment by ralyodio** [comment]
you mean ollama.com right? THat is what we should be integrating with. Their api is nearly identical to openai.

you can test here: https://ai.profullstack.com/api

here's open-ui -- https://ai.profullstack.com

**Comment by air55555** [comment]
> you mean ollama.com right? THat is what we should be integrating with. Their api is nearly identical to openai.
> 
> you can test here: https://ai.profullstack.com/api
> 
> here's open-ui -- https://ai.profullstack.com
> 
> you can download models from huggingface.co with just `ollama pull <model-name>`

great starting point , yeahh , welcome to contribute!

**Comment by zaverichintan** [comment]
I want to make a PR request - kindly add me to the repo

**Comment by ralyodio** [comment]
Just fork it.

**Comment by zaverichintan** [comment]
PR submitted: https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/pull/195

**Comment by air55555** [comment]
> submitted

Thanks for fast development , testing.

**Comment by zaverichintan** [comment]
This issue can be closed as the PR is merged in V3 branch
