### ISSUE TITLE
resume are nothing but lies

### ISSUE THREAD

**Issue by ralyodio** [feder-cr/linkedIn_auto_jobs_applier_with_AI#191]
Here's my original (that I use normally):

https://0x0.st/Xvxo.pdf

Now here's the AI generated garbage that lies about almost everything on my resume.

https://0x0.st/XvxH.pdf

**Comment by air55555** [comment]
hmmm, hallucination, we're working on this. Try again please ,AI just a probability, next runs could be differ.

**Comment by ralyodio** [comment]
no they are all this way.

**Comment by ralyodio** [comment]
you need to explicitly prompt the ai to not fabricate stuff that isn't in the original resume.

**Comment by ralyodio** [comment]
you can also tell it to instead say "willing to learn" for things in the JD that aren't on my resume.

**Comment by azjz92** [comment]
Hey, we're working on this for the next version, feel free to join the dev channel, we'd appreciate your help! https://t.me/+Fc3N65fyz4xmMWQ0

**Comment by air55555** [comment]
@ralyodio Makes sense. Adding to backlog
