### ISSUE TITLE
Documentation TODO: Add necessary documents to README document section

### ISSUE THREAD

**Issue by earl562** [feder-cr/linkedIn_auto_jobs_applier_with_AI#193]
New users are having same persistent issues with navigate repo in the beginning & to mitigate this issue, the best solution would be to add clear and concise answers/docs.

**Comment by ralyodio** [comment]
@earl562 what specific questions do they have? We could add an FAQ to the readme.

**Comment by earl562** [comment]
**Issue has been completed, pull request submission merged w/v3:** [](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/pull/217)
