### ISSUE TITLE
 Error parsing YAML file

### ISSUE THREAD

**Issue by keshav-kumar-01** [feder-cr/linkedIn_auto_jobs_applier_with_AI#198]
All my YMAL code is correct and running the `python main.py` i am getting error parsing YAML file and don't know what to do and how to do please help

**Comment by ralyodio** [comment]
what error?

**Comment by janmejayspurohit** [comment]
plain_text_resume.yaml exam field should have proper values or can be empty.
leave it as `exam:`

i would recommend using the guide to fill in the values in all fields. avoid using empty values or ""

**Comment by air55555** [comment]
@keshav-kumar-01 did you solve? Than close the issue please.

**Comment by keshav-kumar-01** [comment]
> what error? also post your yaml files.

![image](https://github.com/user-attachments/assets/1fdfac84-0482-41bc-b868-7672b8e1e5c6)

**Comment by keshav-kumar-01** [comment]
> plain_text_resume.yaml exam field should have proper values or can be empty. leave it as `exam:`
> 
> i would recommend using the guide to fill in the values in all fields. avoid using empty values or ""

it's not blank

**Comment by keshav-kumar-01** [comment]
I have fixed it and it has started applying , thank you

**Comment by keshav-kumar-01** [comment]
thank you all
