### ISSUE TITLE
notice period not handled

### ISSUE THREAD

**Issue by us** [feder-cr/linkedIn_auto_jobs_applier_with_AI#20]
its discarding application when asked notice period!

**Comment by feder-cr** [comment]
please an example, and link of job

**Comment by triarkact** [comment]
I'll like to have some tips on how's I can use this project features to create a sample of my Web Link

**Comment by feder-cr** [comment]
@triarkact If you’re interested, I’d like to invite you to join our AIHack Telegram community. It’s a fantastic space where you can:

Get answers to your questions
Propose new ideas
Exchange tips and advice with other users of our software
🌟 Join our community here -> https://t.me/AIhawkCommunity
