### ISSUE TITLE
ModuleNotFoundError: no module named 'yaml

### ISSUE THREAD

**Issue by naskaraaryarohit** [feder-cr/linkedIn_auto_jobs_applier_with_AI#201]
Traceback (most recent call last) :
File "/Users/xyz/Documents/JOBS/LinkedIn_AIHawk_automatic_job_application/main.py", line 5, in <module> import yaml
ModuleNotFoundError: no module named 'yaml'

<img width="1554" alt="Screenshot 2024-09-01 at 1 59 34 AM" src="https://github.com/user-attachments/assets/4d8feb79-f5aa-459b-944c-cbe93aa676c1">

**Comment by MAWAAW** [comment]
`pip install pyyaml`

**Comment by air55555** [comment]
@naskaraaryarohit did you solve? Than close the issue please.

**Comment by naskaraaryarohit** [comment]
No i have installed pyyaml in my MAC but the issue still persists

**Comment by Faisals3** [comment]
Add this to your main.py :
import sys
sys.path.append('{YOUR_PATH_TO_PROJECT}/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages')
import yaml

**Comment by vxb200009** [comment]
Same Issue and the issue persists even after the above code added to main

**Comment by feder-cr** [comment]
@vxb200009 @Faisals3 @naskaraaryarohit join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
