### ISSUE TITLE
Add "max_submissions" parameter to limit the number of CVs sent

### ISSUE THREAD

**Issue by MAWAAW** [feder-cr/linkedIn_auto_jobs_applier_with_AI#203]
**Context:** The script currenty runs indefinitely, sending CVs until manually stopped. This can be inconvenient if a user wants to limit the number of applications.

**Proposal:** Add a _max_submissions_ parameter to specify the maximum number of CVs to send. The script will stop automatically once this limit is reached. If not specified, it will continue to run indefinitely as it does now.

**Example:**
- Send up to 10 CVs: _python main.py --max_submissions=10_
- Default behavior (indefinite): _python main.py_

**Comment by shivamkrsarin1996** [comment]
+1 
This is  a good feature if a user wants to run the tool for only specific applications 
Would like a functionality to specify  # of position to apply for

**Comment by feder-cr** [comment]
@MAWAAW ddo you want wokr on this?

**Comment by queukat** [comment]
also there is a limit on linkedin: 100 or 200 applies in 24 hours

**Comment by feder-cr** [comment]
> also there is a limit on linkedin: 100 or 200 applies in 24 hours

200
