### ISSUE TITLE
Cannot see any jobs actually applied

### ISSUE THREAD

**Issue by Huwaiza** [feder-cr/linkedIn_auto_jobs_applier_with_AI#205]
`Applying to jobs on this page has been completed!` But When i visit my applied tabs i don't see any jobs that it applied to, also how can i see the AI generated resume that was used though?

**Comment by azjz92** [comment]
One way to do it currently before we add more features, is to click on the attached generated CV's right before a linkedin app is sent, It will show your resume history there and you can grab it. Keep an eye out for future versions here though, and try V3 in which we are testing new features :)
