### ISSUE TITLE
Feature Request: Mark completed application as Applied 

### ISSUE THREAD

**Issue by shivamkrsarin1996** [feder-cr/linkedIn_auto_jobs_applier_with_AI#206]
When an application is applied, LinkedIn asks if the application was completed or not as Yes, or No to show the status as Applied. 
Add a feature to support the functionality of marking it as Applied once the application is created

**Comment by feder-cr** [comment]
@shivamkrsarin1996 
Do you w
Any work on this? join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
