### ISSUE TITLE
Delay in OpenAI tier upgrade causes runtime errors

### ISSUE THREAD

**Issue by anton6tak** [feder-cr/linkedIn_auto_jobs_applier_with_AI#208]
According to [this discussion](https://community.openai.com/t/usage-tier-free-to-tier-1/919150), the free tier does not immediately update to Tier 1 after purchasing credits for your OpenAI organization. This delay can cause errors during the bot's operation, such as:

`Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}` 

`{'error': {'message': 'Rate limit reached for gpt-4o-mini in organization <org> on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}`

It might be helpful to add information about the OpenAI setup and its potential issues to the README.

**Comment by anton6tak** [comment]
I can handle this issue

**Comment by air55555** [comment]
> I can handle this issue
Thanks for your investigation !
Would be very good Anton if you provide stright guidelines to the Community, how to deal with that !

**Comment by anton6tak** [comment]
fixed here https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/pull/223
