### ISSUE TITLE
ModuleNotFoundError: No module named 'lib_resume_builder_AIHawk' in main.py

### ISSUE THREAD

**Issue by amanmishra7ave** [feder-cr/linkedIn_auto_jobs_applier_with_AI#209]
When running the main.py script, I encountered the following error:

Traceback (most recent call last):
  File "/home/groot/Documents/LinkedIn_AIHawk_automatic_job_application/main.py", line 11, in <module>
    from lib_resume_builder_AIHawk import Resume,StyleManager,FacadeManager,ResumeGenerator
ModuleNotFoundError: No module named 'lib_resume_builder_AIHawk'

Title:
ModuleNotFoundError: No module named 'lib_resume_builder_AIHawk' in main.py

Description:
When running the main.py script, I encountered the following error:

"/home/groot/Documents/LinkedIn_AIHawk_automatic_job_application/main.py", line 11, in <module>
    from lib_resume_builder_AIHawk import Resume,StyleManager,FacadeManager,ResumeGenerator
ModuleNotFoundError: No module named 'lib_resume_builder_AIHawk'
It seems that the lib_resume_builder_AIHawk module is missing or not properly included in the repository. Please provide the necessary module or update the instructions on how to install or configure it.

Steps to Reproduce:

Clone the repository.
Run python3 main.py.
Expected Behavior: The script should run without errors.

Actual Behavior: A ModuleNotFoundError is raised, indicating that the lib_resume_builder_AIHawk module is not found.

Environment:

OS: [Ubuntu 24]
Python: 3.11.9

**Comment by aaabulkhair** [comment]
I have the same issue

**Comment by amanmishra7ave** [comment]
https://github.com/amanmishra7ave/Linkedin_Job_Applying_bot

give it a try

**Comment by MAWAAW** [comment]
Based on your previous message, I understand that you have already installed Python and Google Chrome, and you’ve cloned the project repository. Here are the next steps you need to follow:

1. **Activate the Virtual Environment:**
   - First, create a virtual environment if you haven't done so already:
     ```bash
     python -m venv virtual
     ```
   - Then, activate the virtual environment:
     - On macOS and Linux:
       ```bash
       source virtual/bin/activate
       ```
     - On Windows:
       ```bash
       .\virtual\Scripts\activate
       ```

2. **Install the Required Packages:**
   - Once the virtual environment is activated, install the necessary packages specified in the `requirements.txt` file:
     ```bash
     pip install -r requirements.txt
     ```

This will ensure that all dependencies are correctly installed and your environment is set up properly.

**Comment by amanmishra7ave** [comment]
Thank you for the instructions! I've followed the steps, and everything is working as expected. The virtual environment is set up, and the required packages have been installed successfully.

**Comment by klmnankit1511** [comment]
@amanmishra7ave I tried the same method but it's not working for me. Can you provide the proper steps to resolve this error.

**Comment by amanmishra7ave** [comment]
@klmnankit1511  yeah sure

1.  Activate the Virtual Environment:
If you haven't already created a virtual environment, you can do so with the following command:
python -m venv virtual

2. Install the Required Packages:
Once the virtual environment is activated, ensure that all necessary packages are installed by running:
pip install -r requirements.txt

3. Run the Script:
Finally, run the main.py script using Python 3.10 or 3.11:
python3 main.py

This should resolve the error and allow the script to execute successfully.

If you continue to experience issues, make sure that the lib_resume_builder_AIHawk module is properly included in the project, or verify that it is correctly installed as part of the dependencies.

**Comment by feder-cr** [comment]
@MAWAAW thanks bro, write me on telegram!

@aaabulkhair @klmnankit1511 @amanmishra7ave join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
