### ISSUE TITLE
Style Probelm?

### ISSUE THREAD

**Issue by aijazdata** [feder-cr/linkedIn_auto_jobs_applier_with_AI#212]
Runtime error: Error running the bot: 'FacadeManager' object has no attribute 'choose_style'
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

When I typed "python main.py"; I got this above message, now I don't understand why this is happening, could anyone figure this out for me

**Comment by feder-cr** [comment]
@aijazdata reinstall it all over again and follow been the readme!
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
