### ISSUE TITLE
It doesn't apply

### ISSUE THREAD

**Issue by bemird** [feder-cr/linkedIn_auto_jobs_applier_with_AI#213]
Hello guys,

The bot does not apply jobs instaed it saves it for some reason.
![image](https://github.com/user-attachments/assets/edf670f3-2b42-4a4e-bec6-7fbc8c2622bc)

**Comment by nishit2003** [comment]
I am also facing the same issue

**Comment by earl562** [comment]
It doesn't apply to any jobs or certain ones where it can't fill it out correctly? Also, how long are you running the bot for?

**Comment by bemird** [comment]
First I set up my one of the 2 years old centos machine. It worked very slow and it could only apply 15 jobs. Then I installed new ubuntu machine now it ooens linkedin very fast but does not apply any of the jobs (it happened also centos machine too). It doesnt apply just opens job and exit it without applying. I set up ubuntu machine today morning

**Comment by earl562** [comment]
I would try to update google chrome

**Comment by bemird** [comment]
I downloaded chrome today

**Comment by feder-cr** [comment]
reinstall all! and restart, follow the readme
