### ISSUE TITLE
Any way to change the Salary Expectations from USD to any other currency (in my case INR) 

### ISSUE THREAD

**Issue by akshit7165** [feder-cr/linkedIn_auto_jobs_applier_with_AI#214]
I have tried to change this var **salary_range_usd to salary_range_inr** but still I am getting this error: 

```
> PS D:\Linkein-auto-job-apply> python main.py
> Runtime error: Error running the bot: Unexpected error while parsing YAML: 1 validation error for Resume
> salary_expectations.salary_range_usd
>   Field required [type=missing, input_value={'salary_range_inr': '1200000'}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.8/v/missing
> Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration 
```

Please let me know how to fix this.

Thanks!

**Comment by earl562** [comment]
<img width="339" alt="Screenshot 2024-09-01 at 12 20 42 PM" src="https://github.com/user-attachments/assets/493a741a-f899-4d59-88a7-9dcc57a52984">
Did you pip install yaml? and or all the necessary installs?

**Comment by akshit7165** [comment]
Yes, I have installed all the pre-requisite. I added the INR var too in addition to the USD one throughout the project. After that it started to work. But not sure why I cannot use just INR in place of USD

**Comment by feder-cr** [comment]
@akshit7165 I don't rule out that it already does it automatically
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
