### ISSUE TITLE
Does not apply and no status for applied jobs

### ISSUE THREAD

**Issue by nandishaivalli** [feder-cr/linkedIn_auto_jobs_applier_with_AI#215]
I trued running the model. It starts and says appling for from 0 page and takes a sleep and nothing is applied in likedlin.
I tired both with and without --resume but after 1 page it seems to have stuck on a loop or something.

**Comment by nandishaivalli** [comment]
Is it possible to add other ways to use opensource apis other than gpt?

**Comment by amit99911** [comment]
![image](https://github.com/user-attachments/assets/df0e457e-d76c-425f-bcba-027b08826d5f)
After selecting "Create your Resume Style in CSS" as deafault my whole ubunutu page is blacked out and no response for hours can you please suggest what should be the troubleshoot required?

**Comment by feder-cr** [comment]
Create your Resume Style in CSS is only if you want create a new stile, if you havent a desktop, is impossible redirect do the tutorial for this!

@amit99911 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
