### ISSUE TITLE
Add more details about the chrome drivers

### ISSUE THREAD

**Issue by Aadik1ng** [feder-cr/linkedIn_auto_jobs_applier_with_AI#216]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-easy-apply-content"}
  (Session info: chrome=128.0.6613.114)

**Comment by feder-cr** [comment]
restart the bot @Aadik1ng 
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
