### ISSUE TITLE
Main.py

### ISSUE THREAD

**Issue by John211998** [feder-cr/linkedIn_auto_jobs_applier_with_AI#218]
When i give python main.py --resume path to my resume nothing happens

**Comment by earl562** [comment]
![telegram-cloud-photo-size-1-5089428438242143564-y](https://github.com/user-attachments/assets/dd643c93-43ab-4791-8b5d-c244aa84d0f3)

**Comment by earl562** [comment]
Your resume should be included in your data_folder as shown above, also make sure you're inputting the command/path correctly

**Comment by amasick** [comment]
python main.py --resume /home/kaushik/Desktop/resume_projects/linkedin-automted_apply/LinkedIn_AIHawk_automatic_job_application/data_folder/Aug_DS_Resume_Aman_Kaushik .pdf

Same issue with me too
my command and path both are correct, still on entering this, nothing happens

**Comment by Sartaj2019** [comment]
same here , i have tried to generated resume but also after nothing happen after prompt that which template you wanna use

**Comment by Youplala** [comment]
> python main.py --resume /home/kaushik/Desktop/resume_projects/linkedin-automted_apply/LinkedIn_AIHawk_automatic_job_application/data_folder/Aug_DS_Resume_Aman_Kaushik .pdf
> 
> Same issue with me too my command and path both are correct, still on entering this, nothing happens

Are you sure your path is correct with the space before the `.pdf`?

**Comment by Sartaj2019** [comment]
> > python main.py --resume /home/kaushik/Desktop/resume_projects/linkedin-automted_apply/LinkedIn_AIHawk_automatic_job_application/data_folder/Aug_DS_Resume_Aman_Kaushik .pdf
> > Same issue with me too my command and path both are correct, still on entering this, nothing happens
> 
> Are you sure your path is correct? In your answer there is a space before the `.pdf`

Yeah path is correct, even i tried using auto generated resume option also using "python main.py" i got this but no command works after this 
![autoshot](https://github.com/user-attachments/assets/60d68971-1395-462a-abf3-d416c086759c)

**Comment by azjz92** [comment]
Try downloading v3, I had some issues before but the current version of v3 fixed it. Let me know if that doesn't work.

**Comment by akbhatisain** [comment]
Hi, 
I have tried the main branch and the v3 branch both.
I have tried the following:- 
(virtual) MacBook-Air-2 linkedIn_auto_jobs_applier_with_AI % python3.11 main.py
(virtual) MacBook-Air-2 linkedIn_auto_jobs_applier_with_AI % python main.py
(virtual) MacBook-Air-2 linkedIn_auto_jobs_applier_with_AI % python3.11 main.py --resume ./data_folder/plain_text_resume.yaml

All are giving me the same error : 
Runtime error: Error running the bot: Error parsing YAML file.
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

I am using MacBook m1 series, python multiple version installed but I have set the default version as Python 3.11.
Any help @feder-cr @earl562  @azjz92 

Thanks

**Comment by prvshah51** [comment]
> All are giving me the same error : Runtime error: Error running the bot: Error parsing YAML file. Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

As the error says, try checking if your yaml file is properly formatted, maybe try to copy the files from `data_folder_emaple` again and edit it.
