### ISSUE TITLE
still not fixed, redownloaded and tried with demo file - same error

### ISSUE THREAD

**Issue by ayushiimishra** [feder-cr/linkedIn_auto_jobs_applier_with_AI#219]
still not fixed, redownloaded and tried with demo file - same error

_Originally posted by @Dmorok in https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/89#issuecomment-2322233594_
         same error not getting fixed

**Comment by earl562** [comment]
I have deleted the project entirely and gitconed it again, did you pip install all the necessary requirements? Also, provide a screenshot of the error again.

**Comment by feder-cr** [comment]
@ayushiimishra any update? join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
