### ISSUE TITLE
Updating .gitignore

### ISSUE THREAD

**Issue by VanshWadhwa** [feder-cr/linkedIn_auto_jobs_applier_with_AI#221]
Need to update .gitignore and folder structure so that whenever you pull the changes it don't have merge conflict with your profile data and generated output folder.

**Comment by VanshWadhwa** [comment]
Would like to work on this, can I assign it to myself?

**Comment by feder-cr** [comment]
@VanshWadhwa yes, for sure, join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by VanshWadhwa** [comment]
@feder-cr Thank you, already in 😄
