### ISSUE TITLE
My resume instead of a generated one

### ISSUE THREAD

**Issue by varunk47** [feder-cr/linkedIn_auto_jobs_applier_with_AI#226]
Can I add my own resume pdf instead of using this generated one because it is hallucinating a lot. If yes, can someone please provide the code for that?

**Comment by thpgoncalves** [comment]
Look at the end of the README.md, under the Usage section.

LinkedIn language To ensure the bot works, your LinkedIn language must be set to English.

Data Folder: Ensure that your data_folder contains the following files:

secrets.yaml
config.yaml
plain_text_resume.yaml
Run the Bot:

LinkedIn_AIHawk offers flexibility in how it handles your pdf resume:

Dynamic Resume Generation: If you don't use the --resume option, the bot will automatically generate a unique resume for each application. This feature uses the information from your plain_text_resume.yaml file and tailors it to each specific job application, potentially increasing your chances of success by customizing your resume for each position.

python main.py

Using a Specific Resume: If you want to use a specific PDF resume for all applications, place your resume PDF in the data_folder directory and run the bot with the --resume option:

python main.py --resume /path/to/your/resume.pdf
