### ISSUE TITLE
Error parsing YAML file

### ISSUE THREAD

**Issue by thpgoncalves** [feder-cr/linkedIn_auto_jobs_applier_with_AI#227]
Runtime error: Error running the bot: Error parsing YAML file.

I've already looked at the other YAML file parsing errors and the solutions, I've tried running the proposed solutions but none of them solved my problem.

I tried redoing it from scratch to see if there was some other error but the problem continued.

Attached are my yaml files. Can anyone help me?

**Comment by sunnydigital** [comment]
paste the files into chatgpt and ask it for any encoding errors

**Comment by thpgoncalves** [comment]
Thanks, that founded the error!

**Comment by vaishnavimule** [comment]
> Thanks, that founded the error!

Hey, I am having the same issue. How did you resolve it?

**Comment by vaishnavimule** [comment]
@thpgoncalves This worked for me. Thank you!

**Comment by naticio** [comment]
use https://www.yamllint.com/ to check the files, if needed copy and paste the examples vs your info in gpt to find the discrepancies
