### ISSUE TITLE
llama3 - is it a solution for ratelimting issues with chatgpt

### ISSUE THREAD

**Issue by rt266** [feder-cr/linkedIn_auto_jobs_applier_with_AI#231]
Is chatgpt really required, can llama 3 be used to get the response for the resume generation. Provided llama 3 is doing, what it is supposed , by running that model locally. So, no rate limiting issues

**Comment by bemird** [comment]
I have also rate limit problem. It says 200 per day

**Comment by abhishekY2401** [comment]
hi @rt266, to migrate from gpt to llama 3 or any other LLM, need to change the entire gpt functions from a different repository linked 👉 [AI Resume Builder](https://github.com/feder-cr/lib_resume_builder_AIHawk/) being used as a utilities in the current repo.

**Comment by feder-cr** [comment]
@abhishekY2401 joi  in our telegram dev group
