### ISSUE TITLE
Add file_name inside failed.json and success.json

### ISSUE THREAD

**Issue by VanshWadhwa** [feder-cr/linkedIn_auto_jobs_applier_with_AI#232]
Adding the file name inside `.json` files can help to create a track of generated resume for each job application
![image](https://github.com/user-attachments/assets/0196dea3-b61b-44db-b8e5-88d4c385f3d5)

**Comment by timeowilliams** [comment]
@VanshWadhwa - can you raise a PR for this (README and a placeholder in `.json` files)?

**Comment by feder-cr** [comment]
@VanshWadhwa are you using your own cv?

**Comment by VanshWadhwa** [comment]
@feder-cr No, using the OpenAI generation

**Comment by feder-cr** [comment]
@VanshWadhwa strange, in theory it should already do this, do you want to work on this bug?

**Comment by VanshWadhwa** [comment]
@feder-cr, Sure, Will fix this.

**Comment by feder-cr** [comment]
@VanshWadhwa any update?
