### ISSUE TITLE
Runtime error: Error running the bot: 'exam'

### ISSUE THREAD

**Issue by diegohd8** [feder-cr/linkedIn_auto_jobs_applier_with_AI#234]
Runtime error: Error running the bot: 'exam'

**Comment by MAWAAW** [comment]
Check that you have correctly followed the installation and configuration procedure, and also look at [this link](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/209#issuecomment-2323389724) about the virtual environment if you are on windows
