### ISSUE TITLE
Feature: Add Support for Other LLMs

### ISSUE THREAD

**Issue by abhishekY2401** [feder-cr/linkedIn_auto_jobs_applier_with_AI#235]
Purpose: To explore the effectiveness of other LLMs for summarizing and creating responses while job searching
Aim: Help job seekers to automate their job hunting process

Work TO BE DONE : Replace OPENAI functions with Cohere functions

Let me know if anyone is willing to take this up or maybe I can take it

**Comment by decodingafterlife** [comment]
Hey, I had a similar idea to add support for other LLM models such as Claude which has a better performance than ChatGPT in various benchmarks and a higher limit on free API usage. We can also explore and work on local models like Llama.

I will be glad to contribute in this...

**Comment by zaverichintan** [comment]
There is new PR merged in v3 which can use Llama, GPT and Claude models
