### ISSUE TITLE
Not want to add a section

### ISSUE THREAD

**Issue by pacman20011** [feder-cr/linkedIn_auto_jobs_applier_with_AI#240]
If I don't have a title blacklist, do I delete "word1" and "word2" and leave that area empty? Do I put "N/A"? Let me know. I also don't want to put in my GPA, can I leave that slot blank as well?

**Comment by feder-cr** [comment]
@pacman20011 blacklist can be white, gpa not fo now!
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
