### ISSUE TITLE
Feature request: review AI-generated resume files before applying

### ISSUE THREAD

**Issue by jessicabartley** [feder-cr/linkedIn_auto_jobs_applier_with_AI#242]
Wonderful project. Thanks for open sourcing it!

I have a feature request. I've previously used ChatGPT to manually tailor my resume to job apps but have noticed it has a bad habit of making up experiences/facts about me that are not true. I love that AI Hawk can speed up the job application process by automating app submissions but would feel more comfortable using it if I could review the tailored resumes it generates *before* they are submitted to a company.

Relatedly, once a job applications is submitted, I would love to be able to have access to the documents AI Hawk submitted with my application so that I can reference it if the company sends an interview request.

Thanks!

**Comment by feder-cr** [comment]
@jessicabartley you ca use your cv, please read readme!
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
