### ISSUE TITLE
How do I know it's working?

### ISSUE THREAD

**Issue by pacman20011** [feder-cr/linkedIn_auto_jobs_applier_with_AI#243]
So I got to the end of this where I used the command "python main.py --resume /path/to/resume.pdf" with my resume path included of course, and it took a second then nothing. How do I know it's running? Please let me know how I can check.

**Comment by pacman20011** [comment]
@qWorld-Machine Yes I put my resume in the data_folder and also pasted the path after the flag --resume. But when I hit enter nothing happened, chrome didn't open, I got no error message, nothing. What am I doing wrong?

**Comment by pacman20011** [comment]
@qWorld-Machine 
I got this:
Configuration error: Invalid type for key 'remote' in config file data_folder/config.yaml. Expected <class 'bool'>.
Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by pacman20011** [comment]
@qWorld-Machine Yes and I had it set to "remote: true" but maybe there was something weird with it. I just retyped it as "remote: false", let me try it again.

**Comment by pacman20011** [comment]
@qWorld-Machine Here's what it looks like
<img width="732" alt="Screen Shot 2024-09-02 at 4 16 52 PM" src="https://github.com/user-attachments/assets/f3583586-b4e6-4fdc-98a9-e6f84318676d">

**Comment by pacman20011** [comment]
@qWorld-Machine I tried to run it again and it said the same error for remote in config

**Comment by feder-cr** [comment]
@pacman20011 followe readme or join telegram group

**Comment by pacman20011** [comment]
@feder-cr What is in the telegram group that will be different than here? I don't have telegram so that will be a whole process for me. Will I be able to speak to you directly in the Telegram? I need more information, trying to figure this out.
