### ISSUE TITLE
Rate Limit Errors and KeyError for Missing Sections During Job Application Process

### ISSUE THREAD

**Issue by Pradyumna-yes** [feder-cr/linkedIn_auto_jobs_applier_with_AI#248]
I am encountering issues related to rate limits and missing sections when using the LinkedIn auto-job applier. Here are the details:

1. Rate Limit Errors: The script frequently encounters rate limit errors from the GPT-4 API during the job application process. The specific errors are as follows:

Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-VWLqaGppRpiv9cs2PWks2apV on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}
![image](https://github.com/user-attachments/assets/be2d899a-7304-4807-ae86-0f6b24b58dab)

Despite implementing delays between API calls, the rate limit errors still occur, especially when multiple API requests are made in a short period.

2. KeyError for Missing Sections: In addition to the rate limit issue, I am also facing a KeyError when the script attempts to access the 'education' section in the generated results. It seems that sometimes the section is not present, leading to the following error:

KeyError: 'education'

This error occurs when the script tries to generate a resume or upload it during the job application process.

**Comment by feder-cr** [comment]
@Pradyumna-yes join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
