### ISSUE TITLE
Rate limit reached for gpt-4o-mini

### ISSUE THREAD

**Issue by dhruvil267** [feder-cr/linkedIn_auto_jobs_applier_with_AI#249]
side_projects generated an exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-OOhFjD3fpmItZTQAxWOQx11o on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}
work_experience generated an exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-OOhFjD3fpmItZTQAxWOQx11o on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}
additional_skills generated an exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-OOhFjD3fpmItZTQAxWOQx11o on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}

**Comment by rahulmakwana32** [comment]
I added time.sleep for 60 secs before chain.invoke for now

**Comment by rahulmakwana32** [comment]
Duplicate : https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/248

**Comment by feder-cr** [comment]
@rahulmakwana32 @dhruvil267 you have to wait for openai to raise your limits.
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by dhruvil267** [comment]
@rahulmakwana32 

> I added time.sleep for 60 secs before chain.invoke for now

before all the chain.invoke?
