### ISSUE TITLE
Form not proceeding </button> is not clickable at point 

### ISSUE THREAD

**Issue by rahulmakwana32** [feder-cr/linkedIn_auto_jobs_applier_with_AI#251]
I could see below error and noticed this when form was asking to enter city   this was for job   "[Engineering Manager, DashPass Benefits] 

raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Continue to next step" id="ember460" class="artdeco-button artdeco-button--2 artdeco-button--primary ember-view" data-easy-apply-next-button="" type="button">...</button> is not clickable at point (1154, 319). Other element would receive the click: <div class="search-typeahead-v2__hit search-typeahead-v2__hit--autocomplete" data-test-single-typeahead-entity-form-search-result="true">...</div>
  (Session info: chrome=128.0.6613.114)
Stacktrace:

**Comment by queukat** [comment]
fixed in
https://github.com/queukat/linkedIn_auto_jobs_applier_with_AI/tree/v3

the problem was that it needs to be clicked on city after it been filled
