### ISSUE TITLE
Problem with browser Chrome

### ISSUE THREAD

**Issue by AndreyCoder404** [feder-cr/linkedIn_auto_jobs_applier_with_AI#257]
for some reason the bot launches a different version of the Chrome browser, which is why I can't log in (it says: This browser or app may not be secure. Learn more
Try using a different browser. If you're already using a supported browser, you can try again to sign in.)
Although when I launch the browser myself and go to the site, there are no problems. But when the bot starts working, it also launches the Chrome browser, although even by the interface in the browser I can tell that it is a different Chrome

**Comment by AndreyCoder404** [comment]
even deleting chrome and downloading it again didn't give any result

**Comment by behole** [comment]
What was the solution here if you dont mind me asking? I am running into the same issue.
