### ISSUE TITLE
Resume Style CSS

### ISSUE THREAD

**Issue by aijazdata** [feder-cr/linkedIn_auto_jobs_applier_with_AI#258]
As soon as I have applied all the instrcutions which were given in the video, and when I typed python main.py
It gives me this:

 Which style would you like to adopt?:
 > Modern (style author -> https://github.com/blaketylerfullerton)
   Modern Blue (style author -> https://github.com/josylad)
   Modern Grey (style author -> https://github.com/josylad)
   Default (style author -> https://github.com/krishnavalliappan)
   Create your resume style in CSS
   
   
   Could anyone or the owner say me what should I choose?

**Comment by feder-cr** [comment]
@aijazdata what do you prefer
