### ISSUE TITLE
plain_text_resume.yaml is not required if there is a custome resume file

### ISSUE THREAD

**Issue by medaminefh** [feder-cr/linkedIn_auto_jobs_applier_with_AI#262]
Even if you specify the resume path, you will be faced an error if there is in your `plain_text_resume.yaml`

**Comment by feder-cr** [comment]
@medaminefh do you want work on this?

**Comment by digs1998** [comment]
the plain_text_resume file does not customize based on the role, in the readme it was mentioned, that if you wish to run command that also personalizes your resume, run `main.py`. Does that happen for you guys?
