### ISSUE TITLE
Runtime error: Error running the bot: Error parsing YAML file

### ISSUE THREAD

**Issue by vinayb97** [feder-cr/linkedIn_auto_jobs_applier_with_AI#265]
When running main.py on the terminal,

(virtual) (/Users/vinay/opt/anaconda3) Vinays-MacBook-Pro:LinkedIn_AIHawk_automatic_job_application vinay$ python main.py
Runtime error: Error running the bot: Error parsing YAML file.
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

It shows this error. I double checked my syntax in the yaml file and my inputs.

Please help.

Current system: 

Python version 3.12.3
MacBook Pro (mid 2012) Version: 10.15.7

**Comment by feder-cr** [comment]
@vinayb97 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
