### ISSUE TITLE
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

### ISSUE THREAD

**Issue by RichBOwens** [feder-cr/linkedIn_auto_jobs_applier_with_AI#268]
When running the bot, I got the following error:
<img width="587" alt="Screenshot 2024-09-03 at 2 02 38 PM" src="https://github.com/user-attachments/assets/8281e992-29e0-491e-b472-dfaf9e265521">

**Comment by feder-cr** [comment]
Please follow readme
