### ISSUE TITLE
Configuration error:

### ISSUE THREAD

**Issue by sniperstrange** [feder-cr/linkedIn_auto_jobs_applier_with_AI#270]
Invalid type for key 'remote' in config file data_folder\config.yaml. Expected <class 'bool'>. Refer to the configuration guide for troubleshooting
 
 checked the config.yaml and its fine

**Comment by RichBOwens** [comment]
Having the same issue. Ran the YAML syntax through the check and no errors were found.

**Comment by djuliette** [comment]
I came here to ask the same thing.

**Comment by prvshah51** [comment]
Can you put a screenshot of the file ?

**Comment by feder-cr** [comment]
@sniperstrange @djuliette @prvshah51 @RichBOwens join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
