### ISSUE TITLE
Randomly filling questionnairs.

### ISSUE THREAD

**Issue by SaadKhalidAlarifi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#278]
When asked 'how many years of experience using x?' it tends to give either a 2 or a 4, although is not true and not specified by myself.

**Comment by pafthinder** [comment]
hehe, I don't mean to be mean, but if the bot gives responses like this 

```
{
        "type": "radio",
        "question": "do you have a valid driver's license?do you have a valid driver's license?requiredyesno",
        "answer": "no"
    },
    {
        "type": "numeric",
        "question": "how many years of appliances, electrical, and electronics manufacturing experience do you currently have?",
        "answer": 1
    },
    {
        "type": "numeric",
        "question": "how many years of work experience do you have with java?",
        "answer": 2
    },
    {
        "type": "numeric",
        "question": "what are your salary expectations [pln]? - in case if you are interested in contract of employment, provide gross salary/month or net/h in case of b2b",
        "answer": 15
    },
    {
        "type": "numeric",
        "question": "what is your notice period [months]?",
        "answer": 2024
    }
```

**"question": "what is your notice period [months]?",
"answer": 2024**
lol xd 

"question": "how many years of work experience do you have with java?",
"answer": 2
even tough I have no a single mention of java in my whole CV 

that's totally waste application and therefore time in my opinion 

and don't wanna hate, so I'll take a look and see there is some way to troubleshoot this. 
I will update this post if am able to make the answers more... down to earth and legit.

**Comment by JimWas** [comment]
I agree that we need to be able to have some direction on how to respond. I am going in and changing already answered questions but minimum years experience should be a field as it's typing 2 when I have 10. Any way to fix this in advance?

**Comment by feder-cr** [comment]
@JimWas @SaadKhalidAlarifi we need fix the prompt, but balancing this is very difficult, join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
