### ISSUE TITLE
Limit reached error

### ISSUE THREAD

**Issue by Sartaj2019** [feder-cr/linkedIn_auto_jobs_applier_with_AI#279]
when run query with python main.py . it gave me error of reaching out the limit for gpt-4o-mini, although i have prepaid for the API usage on openAI website . if i use my own resume then i worked fine for few applications . but auto generation it throw me an error 
error:
side_projects generated an exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-erQx1ZrQBcN6XYo3YE on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}
achievements generated an exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-erQx1ZrQBcN6XYo3YEN on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}

**Comment by smarabattula** [comment]
I faced the same issue as well.

**Comment by pChitral** [comment]
@Sartaj2019 this has got nothing to do with the code, but just the rate limits from openai. One thing that you can do it set a semaphore on how many reqs you will make in the certain window wrt your own rate limits that you can find on your openai portal. 

I will try to raise a pr to gracefully handle the rate limits

**Comment by feder-cr** [comment]
@Sartaj2019 @pChitral @smarabattula join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
