### ISSUE TITLE
Runtime error: Error running the bot

### ISSUE THREAD

**Issue by DewanggaDew** [feder-cr/linkedIn_auto_jobs_applier_with_AI#280]
Runtime error: Error running the bot: Failed to initialize browser: [WinError 193] %1 is not a valid Win32 application

I ran into this problem when execution the main.py

**Comment by Thenewchicken55** [comment]
Do you have chrome installed in your environment?

**Comment by feder-cr** [comment]
@cyb3r-n3rd @Thenewchicken55 @DewanggaDew join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
