### ISSUE TITLE
cant get it to choose wanted leagal_authorization option

### ISSUE THREAD

**Issue by brightdo** [feder-cr/linkedIn_auto_jobs_applier_with_AI#281]
Hi I have following options set for legal_authorization in plain_text_resume.yaml
legal_authorization:
  eu_work_authorization: "Yes"
  us_work_authorization: "Yes"
  requires_us_visa: "no"
  requires_us_sponsorship: "Yes"
  requires_eu_visa: "Yes"
  legally_allowed_to_work_in_eu: "Yes"
  legally_allowed_to_work_in_us: "Yes"
  requires_eu_sponsorship: "Yes"

but  when I check the bot applying on LinkedIn, I see It keeps ticking NO on option for Are you legally authorized to work in the United States?
What is the correct format to make it tick Yes on "legally authorized to work in the US and Yes on "Will you now or in the future require sponsorship for employment visa status (e.g. H-1B visa status)?"

**Comment by queukat** [comment]
find this question in answers.json and fix it
