### ISSUE TITLE
Can  non-easy-apply linkdin jobs can be considered for including in this project

### ISSUE THREAD

**Issue by rt266** [feder-cr/linkedIn_auto_jobs_applier_with_AI#286]
Can  non-easy-apply linkedin jobs can be considered for including in this project.
There is a simplify Jobs chrome extension, can it be taken as an inspiration and generation of customized resumes and applied.

**Comment by pChitral** [comment]
It would be laborious to generalize all the form types but we can start support the popular ones (greenhouse, workday, etc) what are your thoughts on it?

**Comment by azjz92** [comment]
Definitely considered. Keep an eye out for future editions :)
