### ISSUE TITLE
How to verify that it actually applied for jobs

### ISSUE THREAD

**Issue by ehiaig** [feder-cr/linkedIn_auto_jobs_applier_with_AI#291]
I ran the script, no error, no logs, nothing.
Is there a way to verify that it actually found jobs and applied for them?
It would be great to have that as part of the documentation
<img width="787" alt="Screenshot 2024-09-05 at 17 39 27" src="https://github.com/user-attachments/assets/586d5062-6139-4d16-9a5c-f365cab32300">

**Comment by arjunhm** [comment]
#243

**Comment by row2noob** [comment]
You can find it under Jobs-My Jobs-Applied on LinkedIn.

**Comment by azjz92** [comment]
also there should be a failed and success output file in the data folder, we will eventually have a more robust and improved way to log this.
