### ISSUE TITLE
Input Email is different from resume.yaml

### ISSUE THREAD

**Issue by cinque-tsai** [feder-cr/linkedIn_auto_jobs_applier_with_AI#292]
Thanks in advance for the codes and any advice.

My issue is that the bot is input my email with chatgpt, not my default email for linkedin.

Is there a way to avoid this?

**Comment by prvshah51** [comment]
Hi, I am not the author or a contributor but would like to help you out. As far as I know the email you add in the `secrets.yaml` is only used to login in to linked in, after that every input is taken from the `plain_text_resume.yaml` . Let me know if that helps? Or we can dig a bit more into the issue.

**Comment by cinque-tsai** [comment]
Thanks for your reply.
However, after making sure I am using the right email in my resume.yaml, the bot is still inputing my chatgpt email. I wonder if I  can prevent this throught chatgpt project?

**Comment by cinque-tsai** [comment]
> Hi, I am not the author or a contributor but would like to help you out. As far as I know the email you add in the `secrets.yaml` is only used to login in to linked in, after that every input is taken from the `plain_text_resume.yaml` . Let me know if that helps? Or we can dig a bit more into the issue.
