### ISSUE TITLE
Not sure what to do 

### ISSUE THREAD

**Issue by brsobelman** [feder-cr/linkedIn_auto_jobs_applier_with_AI#294]
When i run this in a git bash i keep on running into this issue where it gives me a selection but i can't select. Am i stupid? or just overr looking something?
![image](https://github.com/user-attachments/assets/52bd01e7-cb51-45d6-b0f3-d62039cb4541)

[?] Which style would you like to adopt?:
 > Modern (style author -> https://github.com/blaketylerfullerton)
   Modern Blue (style author -> https://github.com/josylad)
   Modern Grey (style author -> https://github.com/josylad)
   Default (style author -> https://github.com/krishnavalliappan)
   Create your resume style in CSS

**Comment by xyanglu** [comment]
I use the arrow keys to select my choice and then I press `Enter`, does it not work for you? Try using a different terminal maybe

**Comment by brsobelman** [comment]
> I use the arrow keys to select my choice and then I press `Enter`, does it not work for you? Try using a different terminal maybe

Had to use the Windows Terminal. TY
