### ISSUE TITLE
Allow Custom Resume Filename Generation with Duplicate Handling

### ISSUE THREAD

**Issue by chandrahasminajigi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#300]
Currently, resume filenames are generated in the format CV_random_number. This update should enable the following functionality:

1. Allow the user to specify a desired filename for the generated resume.
2. If the desired filename already exists, move the existing file to an "old resumes" directory.
3. When moving the old file, append a random number to ensure uniqueness in the "old resumes" directory.
4. The newly generated resume should be saved with the desired filename and will be used to apply for a job.

**Comment by queukat** [comment]
give example, please

bot creates a new resume for each job
so, there are two ways:
1. in "generated_cv" will always be only one resume
2. user supposed to enter multiple names for resumes (i.e. CV_name_1, name_2, name_3)

**Comment by feder-cr** [comment]
@chandrahasminajigi join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
