### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by harshit56** [feder-cr/linkedIn_auto_jobs_applier_with_AI#303]
Runtime error: Error running the bot: Failed to initialize browser: Message: session not created
from unknown error: failed to write prefs file
Stacktrace:
#0 0x55701397b86a <unknown>
#1 0x557013649e50 <unknown>
#2 0x55701368683e <unknown>
#3 0x557013686a91 <unknown>
#4 0x5570136806c1 <unknown>
#5 0x55701367dc78 <unknown>
#6 0x5570136ca64e <unknown>
#7 0x5570136c9e66 <unknown>
#8 0x5570136be233 <unknown>
#9 0x55701368c093 <unknown>
#10 0x55701368d09e <unknown>
#11 0x557013942acb <unknown>
#12 0x557013946a81 <unknown>
#13 0x55701392e695 <unknown>
#14 0x5570139475f2 <unknown>
#15 0x55701391386f <unknown>
#16 0x55701396a668 <unknown>
#17 0x55701396a832 <unknown>
#18 0x55701397a65c <unknown>
#19 0x7f6662c94ac3 <unknown>

Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

Can someone please help me with this?

Thank you

**Comment by queukat** [comment]
yep, close the browser

right now it can handle only one instance at a time
