### ISSUE TITLE
UK Job Sponsorship question

### ISSUE THREAD

**Issue by 0HisRoyalMajesty0** [feder-cr/linkedIn_auto_jobs_applier_with_AI#309]
In almost all UK job applications, we are asked whether "Are you legally allowed to work in the United Kingdom?"
I tried editing the code and adding lines same as US and EU visas but it seems it didn't work. (No surprise, I have no idea about coding).
![image](https://github.com/user-attachments/assets/448fac8b-05d3-440f-901c-a8bf694c13a0)
In the source code file "job_application_profile.py", I replicated line 15-18 and same changes in "plain_text_resume.yaml" under section "Legal_authorization".
![image](https://github.com/user-attachments/assets/31492e32-41a4-475e-b5a2-642d9657eb2b)

Now, I may have done something totally wrong, this is not working because the bot is submitting all applications as me NOT being allowed to work in UK. 
Can you some please help me fix this, and furthermore please add UK preference to the code file in repository?

Thank you so much!

**Comment by queukat** [comment]
check the answers.json, find this question and change the answer

**Comment by feder-cr** [comment]
@0HisRoyalMajesty0 we are working on this, join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
