### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kulwant-sin** [feder-cr/linkedIn_auto_jobs_applier_with_AI#312]
Getting the below error. Unable to debug. Can someone please help???

(virtual) PS C:\Github\LinkedIn_AIHawk_automatic_job_application> python main.py
Runtime error: Error running the bot: Unexpected error while parsing YAML: 14 validation errors for Resume
personal_information.github
  Field required [type=missing, input_value={'name': 'Kulwant', 'surn...com/in/kulwantsingh28/'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.0.exam
  Field required [type=missing, input_value={'degree': 'Master of Com...dy': 'Computer Science'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.1.degree
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.1.university
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.1.gpa
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.1.graduation_year
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.1.field_of_study
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.2.exam
  Field required [type=missing, input_value={'degree': 'Bachelor of C...dy': 'Computer Science'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.3.degree
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.3.university
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.3.gpa
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.3.graduation_year
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
education_details.3.field_of_study
  Field required [type=missing, input_value={'exam': [{'Information T...B'}, {'Database': '4'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
projects.0.link
  Field required [type=missing, input_value={'name': 'Google Hackatho...deo streaming services'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by queukat** [comment]
For anyone having issues with yaml parsing go to this link and paste your yaml file content: https://www.yamllint.com/
It might  be an issue with your yaml syntax.

**Comment by feder-cr** [comment]
@kulwant-sin join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
