### ISSUE TITLE
Applying to wrong jobs

### ISSUE THREAD

**Issue by rahul-lohra** [feder-cr/linkedIn_auto_jobs_applier_with_AI#314]
Let's say you want to apply for Software Engineer Android role

Code needed to reproduce:
So we need fill this **config.yaml** as 
````
positions:
  - Principle Android Engineer
  - Principle Engineer - Android
  - Android Lead
````
Scenario:

And if the search result does not have any Android Engineer role instead it is showing some general Software Engineer role and internally it has mentioned Backend or AI specific requirements

Problem:
Then the bot will still try to apply

**Comment by feder-cr** [comment]
@rahul-lohra explain better and add 1 example
