### ISSUE TITLE
ChromeBrowserOptions

### ISSUE THREAD

**Issue by manishjangra28** [feder-cr/linkedIn_auto_jobs_applier_with_AI#320]
Traceback (most recent call last):
  File "/Users/xxxx/AI_Linkedin_bot/LinkedIn_AIHawk_automatic_job_application/main.py", line 12, in <module>
    from src.utils import chromeBrowserOptions
ImportError: cannot import name 'chromeBrowserOptions' from 'src.utils' (/Users/xxxx/AI_Linkedin_bot/LinkedIn_AIHawk_automatic_job_application/src/utils.py). Did you mean: 'chrome_browser_options'?

**Comment by feder-cr** [comment]
@manishjangra28 no duplicate, join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
