### ISSUE TITLE
Details not changing while applying Jobs

### ISSUE THREAD

**Issue by manishjangra28** [feder-cr/linkedIn_auto_jobs_applier_with_AI#321]
I have changes the personal details in resume.yaml and also changed config.yaml and it is running successful but when the bot applying the job it is not taking my details instead taking Liam details and also resume of liam not sure why i am getting this issue and i also tried to delete the data_folder_example but same issue.

**Comment by ebe25** [comment]
hey @manishjangra28 similiar issue was happening with me, i deleted the __pychache__ folder and the chrome_details cache folder, removed the data_folder_with_example, deleted the virtual folder, deactivated the virtual env I was on and re-initiated and activated a new virtual env, it worked for me, hope that works for you too, don't forget to run the pip I -r requirements.txt when you activate the new virtual env.

**Comment by manishjangra28** [comment]
Hi @ebe25 thanks for your help i tried and it worked for me but i want to try with my resume and i am using "python3 main.py --resume /data_folder/Manish-resume.pdf  " but it's not working and also not giving any error it just stop after entering the command. Can you please help me in this?

**Comment by ebe25** [comment]
Hey man, could send the error logs on the telegram group, tag my name. Will
take a look.

**Comment by feder-cr** [comment]
@ebe25 @manishjangra28 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
