### ISSUE TITLE
cannot import name 'chromeBrowserOptions' from 'src.utils' 

### ISSUE THREAD

**Issue by manishjangra28** [feder-cr/linkedIn_auto_jobs_applier_with_AI#324]
Traceback (most recent call last):
  File "/Users/xxx/AI_Linkedin_bot/linkedIn_auto_jobs_applier_with_AI/main.py", line 12, in <module>
    from src.utils import chromeBrowserOptions
ImportError: cannot import name 'chromeBrowserOptions' from 'src.utils' (/Users/xxx/AI_Linkedin_bot/linkedIn_auto_jobs_applier_with_AI/src/utils.py). Did you mean: 'chrome_browser_options'?

**Comment by rohanj-0606** [comment]
It is not working for me as well. I have tried on windows as well on mac.

**Comment by rahul-lohra** [comment]
This is a temporary fix for people with this issue: 
Do this change in main.py
Replace the word **chromeBrowserOptions** with **chrome_browser_options** @rohanj-0606 @manishjangra28

**Comment by rohanj-0606** [comment]
I tried the temporary fix which you mentioned however it is showing  the following error now
<img width="1135" alt="Screenshot 2024-09-08 at 7 08 54 PM" src="https://github.com/user-attachments/assets/74016d3a-8fe8-43f9-90e0-5f9efd05c741">

**Comment by rahul-lohra** [comment]
Enter your open ai secret key

**Comment by rahul-lohra** [comment]
Follow this article, to get your secret key: https://medium.com/@lorenzozar/how-to-get-your-own-openai-api-key-f4d44e60c327

**Comment by rohanj-0606** [comment]
Hi Rahul, thank you for your quick response. Where to enter the open api secret key?

I followed the same article and configured my secret key in the secret.yaml file as well. The same config is working in the main branch however it is not working in the v3 branch after doing your temporary fixes. Kindly suggest.

**Comment by rahul-lohra** [comment]
Goto data_folder/secrets.com
enter the value in llm_api_key

**Comment by rahul-lohra** [comment]
Maybe later you might need to add some dollar into your open ai account to make this ai bot work, otherwise you might see some 429 errors from open ai

I tried with 10 dollar and open ai seems to be working just fine @rohanj-0606
