### ISSUE TITLE
 This **problem is related to indentation**. Once your **indentation** in file is same as that of files in data_folder_example. You'll be able to run it.

### ISSUE THREAD

**Issue by madhuptiwari** [feder-cr/linkedIn_auto_jobs_applier_with_AI#328]
@feder-cr This **problem is related to indentation**. Once your **indentation** in file is same as that of files in data_folder_example. You'll be able to run it. Hope this helps.

If in case you get a **runtime error**. That will be due to a parsing error in one of YAML files. I think most people will make errors in resume.yaml file.

Note: Check your code or opening and closing braces. 

_Originally posted by @madhuptiwari in https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/4#issuecomment-2337136759_

**Comment by feder-cr** [comment]
@madhuptiwari i don understand, do you have a error?

**Comment by madhuptiwari** [comment]
No I don't I was answering the other question. I'm deleting this thread, apologies!
