### ISSUE TITLE
File not found: Data folder not found: data_folder

### ISSUE THREAD

**Issue by Bamuve98** [feder-cr/linkedIn_auto_jobs_applier_with_AI#335]
Hi guys, i have this little problem.

I configured all as the video shows, but at the moment when i run the code, shows me the error that says that the folder wasn't found.

![Captura de pantalla 2024-09-09 141257](https://github.com/user-attachments/assets/cc6cc318-c22f-48c1-908c-404f845df5ce)
![Captura de pantalla 2024-09-09 141321](https://github.com/user-attachments/assets/8ce12d9b-83eb-4af2-834c-caa186ca239a)

I dont know if i do something wrong
if someone know how i can fix this, i'll be grateful <3

**Comment by rishabredhu** [comment]
![image](https://github.com/user-attachments/assets/40d39809-a164-4a20-aa09-65535c3f2ca9) - seperate repo ( I have forked one for now - CLI UI buildup). 

Your program is not able to find the data folder.
