### ISSUE TITLE
CV naming suggestion

### ISSUE THREAD

**Issue by njemanzedavid** [feder-cr/linkedIn_auto_jobs_applier_with_AI#337]
Create a new script for CV naming that names CVs this way:

Firstname_lastname_companyname_jobtitle_date

Now, if in the process of saving the resume file, it's finds the name already exist, it can then save like file explorers do, with  number in brackets (but with the date it most likely won't need to)

Also this naming scheme, used on the CVs uploaded to the job applications, in my opinion wont seem as automated or robotic to the recruiter

**Comment by feder-cr** [comment]
@njemanzedavid join in telegram group
