### ISSUE TITLE
Exiting out of application and saving it

### ISSUE THREAD

**Issue by Fredo23** [feder-cr/linkedIn_auto_jobs_applier_with_AI#340]
The bot is working but instead of applying to the jobs it instead is just saving the application

**Comment by rahul-lohra** [comment]
Check the logs, maybe you don't have enough credits in your open ai account

**Comment by PatilHrushikesh** [comment]
Use groq

**Comment by thomHayner** [comment]
possibly duplicate of #313.
also possible triplicate documented in #363 .

@Fredo23 do you have a copy of the output logs when this is happening?

**Comment by feder-cr** [comment]
@thomHayner thanks for your work

**Comment by Fredo23** [comment]
I had to put more credits into my account thank you guys
