### ISSUE TITLE
WebDriver error

### ISSUE THREAD

**Issue by kproudler** [feder-cr/linkedIn_auto_jobs_applier_with_AI#346]
This occurs after selecting the resume type, ceases to run.

`Starting Chrome browser to log in to LinkedIn.
Navigating to the LinkedIn login page...
Login form not found. Aborting login.
WebDriver error occurred: Message: element click intercepted: Element is not clickable at point (1185, 1398)
  (Session info: chrome=128.0.6613.119)
Stacktrace:
#0 0x563888c3d86a <unknown>
#1 0x56388890be50 <unknown>
#2 0x563888962346 <unknown>
#3 0x56388896025d <unknown>
#4 0x56388895dcf7 <unknown>
#5 0x56388895cb9c <unknown>
#6 0x5638889504d6 <unknown>
#7 0x563888980492 <unknown>
#8 0x56388894fe89 <unknown>
#9 0x56388898065e <unknown>
#10 0x56388899e9c6 <unknown>
#11 0x563888980233 <unknown>
#12 0x56388894e093 <unknown>
#13 0x56388894f09e <unknown>
#14 0x563888c04acb <unknown>
#15 0x563888c08a81 <unknown>
#16 0x563888bf0695 <unknown>
#17 0x563888c095f2 <unknown>
#18 0x563888bd586f <unknown>
#19 0x563888c2c668 <unknown>
#20 0x563888c2c832 <unknown>
#21 0x563888c3c65c <unknown>
#22 0x7f16b50d1ac3 <unknown>`

**Comment by feder-cr** [comment]
@kproudler any update?

**Comment by feder-cr** [comment]
@kproudler join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
