### ISSUE TITLE
Phone number and country did not change 

### ISSUE THREAD

**Issue by db2024git** [feder-cr/linkedIn_auto_jobs_applier_with_AI#347]
I have changed the phone number and the country in plain_text_resume.yaml but when i see the bot applying to jobs , It write italy in the country and different phone number.
I apply with my own pdf using python main.py --resume /path/to/your/resume.pdf

![image](https://github.com/user-attachments/assets/e3f84919-ec93-40c3-8ca7-f4c1eacf3873)

**Comment by feder-cr** [comment]
Check on answers.json @db2024git

**Comment by db2024git** [comment]
I changed answers.json but still have the same problem. I even changed the one in the example file. Is there any other places?
