### ISSUE TITLE
bot sleeps before proceeding to next job type/location

### ISSUE THREAD

**Issue by carolinesharpe** [feder-cr/linkedIn_auto_jobs_applier_with_AI#356]
i had 2 locations listed, San Francisco and USA. i also had 7 job titles listed:  
  - Project Manager
  - Product Manager
  - Program Manager
  - Assistant Project Manager
  - Assistant Product Manager
  - Assistant Program Manager
  - Business Analyst
  
except bot just sleeps instead of proceeding to next combination. i have to terminate then restart script to proceed to next search

**Comment by reiiigns** [comment]
same for here, tried to find where the timer is but couldn't locate it
