### ISSUE TITLE
Configuration Error with YAML Parsing - Example File Not Working

### ISSUE THREAD

**Issue by GregFree** [feder-cr/linkedIn_auto_jobs_applier_with_AI#361]
**Description:** I'm encountering persistent issues with the config.yaml file when running the LinkedIn_AIHawk bot. Despite validating the YAML file and using the provided example file, the bot consistently throws errors related to missing or invalid keys in the configuration. Specifically, the bot returns the following errors:

"Missing or invalid key 'jobTypes' in config file data_folder\config.yaml"
"Error parsing YAML file"
These errors occur even after using the example config.yaml provided in the data_folder_example.

**Steps to Reproduce:**

Cloned the repository and followed the instructions in the README.
Used the example config.yaml file from data_folder_example without modifications.
Ran the bot with python main.py in a clean environment.
Encountered repeated errors related to the config.yaml file, including invalid key errors.

**YAML Validation:**

I validated the config.yaml using [YAML Lint](https://www.yamllint.com/), and it passed with no syntax errors.
The file is saved with UTF-8 encoding and LF line endings.
Here is the current content of my config.yaml:

remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: true
  week: false
  24 hours: true

positions:
  - Software Tester

locations:
  - USA

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:

**Troubleshooting Steps Taken:**

Validated the YAML File:

Used an external YAML validator to confirm that the file structure is correct.
Tried reformatting the file, ensuring consistent indentation (2 spaces per level) and correct encoding.
Tried the Example config.yaml:

Directly copied and pasted the config.yaml from the data_folder_example without any changes.
The error persisted, even with the unmodified example file.
Simplified the config.yaml:

Removed sections of the YAML to try and isolate the problematic part. Even with the most basic structure, the bot continued to return parsing errors.
Added Debugging Statements:

Added print statements to the YAML loading function in main.py to see if there was a specific parsing issue. Despite valid YAML, the bot still throws an error related to missing or invalid keys (jobTypes).
Checked Dependencies:

Reinstalled the Python environment and verified that all dependencies, including PyYAML, were up to date.

**Environment:**

OS: Windows 11
Python Version: 3.12.5
PyYAML Version: Latest (installed via pip)
LinkedIn_AIHawk Version: Cloned from the main branch on GitHub
Expected Behavior: The bot should run successfully with the provided example config.yaml, or at least provide more specific details about what is wrong with the file.

Actual Behavior: The bot fails to run and returns the error:

Configuration error: Missing or invalid key 'jobTypes' in config file data_folder\config.yaml

**Request for Help:** Could you please provide guidance or update the bot to clarify the expected structure of config.yaml? It seems like there is an issue with how the bot interprets the YAML file. Any help resolving this would be greatly appreciated, as using the example file doesn't appear to work.

Additional Information:
If you need more details or testing, I'm happy to assist. Thank you in advance for your help!

**Comment by thomHayner** [comment]
@GregFree was it working last week and now it's not?

I had similar errors yesterday after updating my fork.  I wound up cloning the repo from new again and I stopped getting the errors...have you tried that?

- Update your fork from the original (there were some PR's earlier this week).
- Don't push your data_folder with personal details, resume, config or API/LinkedIn keys to your fork, just stash the data_folder files on your desktop.
- Delete your local repo files (but keep the data_folder stashed on your desktop).
- Clone the repo from new again and replace the repo's data_folder config, resume, and secrets files with the data_folder files that you stashed on your desktop.
- Then double check in VS Code, looking at the working file, to make sure that none of the property names changed (I know that in resume/education some names changed, like "university" -> "institution", as well as others).
- As long as you are using the updated property names then start a clean python env, do a pip install, etc and see if it works

**Comment by Antharithm** [comment]
Yeah i had the bot working fine for weeks until i updated to a newer version of the repo. Consistently having this yaml error show up

**Comment by azjz92** [comment]
Yeah just fixed it guys, please try my latest PR and let me know if it works, or go to my fork on yaml updates local. it just did for me :) Message me back if it doesn't work.

**Comment by Antharithm** [comment]
Still not working. When i run the commands to run the bot nothing happens now, not even the parse yaml error
