### ISSUE TITLE
answers.json showing incorrect output

### ISSUE THREAD

**Issue by thomHayner** [feder-cr/linkedIn_auto_jobs_applier_with_AI#362]
I noticed that in the answers.json file, where my address's "state" should have been listed, gender was listed instead.

<img width="410" alt="Screenshot 2024-09-12 at 11 31 26 AM" src="https://github.com/user-attachments/assets/3cec0000-bef5-45a0-b3f9-0554d11ffa7e">

**Comment by feder-cr** [comment]
@thomHayner you can modify this!
