### ISSUE TITLE
bot crashes at the resume upload step

### ISSUE THREAD

**Issue by osamagamal7** [feder-cr/linkedIn_auto_jobs_applier_with_AI#363]
I keep getting this error.
i downloaded Chromedrive and put the path explicitly in `init_browser` function but can't seem to fix it. 

```
def init_browser() -> webdriver.Chrome:
    try:
        options = chromeBrowserOptions()  
        # Use the located path for ChromeDriver
        service = Service("/usr/local/bin/chromedriver")
        return webdriver.Chrome(service=service, options=options)
    except Exception as e:
        raise RuntimeError(f"Failed to initialize browser: {str(e)}")
```

![Screenshot 2024-09-12 at 8 14 51 PM](https://github.com/user-attachments/assets/a4c354ac-650a-4fa9-b85d-b21a0abee2a0)

**Comment by thomHayner** [comment]
#313

**Comment by feder-cr** [comment]
@osamagamal7 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
