### ISSUE TITLE
[BUG]: YAML config

### ISSUE THREAD

**Issue by skaramsi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#376]
### Describe the bug

Im getting the following error: Runtime error: Error running the bot: Error parsing YAML file. Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration, i have used yamllint and also copied and pasted everything from example files. i cant find the issue. please help 

### Steps to reproduce

I am running "python3 main.py"

### Expected behavior

ask me what resume I would like to use

### Actual behavior

i get an error about YAML file Runtime error: Error running the bot: Error parsing YAML file. Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

### Environment

Development

**Comment by Antharithm** [comment]
Yeah same, was working a few PRs ago but now that latest version of this repo the yaml error is persistent

**Comment by Antharithm** [comment]
@feder-cr this should be a top priority fix for v3

**Comment by feder-cr** [comment]
@Antharithm do you want work on this?

join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by Antharithm** [comment]
@feder-cr or @skaramsi please give me PR rights, i fixed this bug and i am trying to push to the yaml branch i created

**Comment by feder-cr** [comment]
Creare a pr to v3

**Comment by ralyodio** [comment]
> @feder-cr or @skaramsi please give me PR rights, i fixed this bug and i am trying to push to the yaml branch i created

you don't need merge access just push a PR from your fork and we'll add it if it works.

**Comment by Antharithm** [comment]
@skaramsi i made a PR it should be merged to the main branch of this repo once @feder-cr approves my changes

**Comment by skw1335** [comment]
Okay im not the only one with this issue ^_^

**Comment by Antharithm** [comment]
@skaramsi and @skw1335 looks like the there is a failure in the python pipeline so my PR was not merged. Best advice i can give until this bug is merged is triple check both the config.yaml and resume file for any indentation or quotes that are out of place. I went through every line and found a few quotes that may have caused my parsing issue

**Comment by skw1335** [comment]
it passed https://www.yamllint.com.

**Comment by Antharithm** [comment]
Also check your resume file too
