### ISSUE TITLE
requirments.txt package Installation Failed

### ISSUE THREAD

**Issue by sai-rohit-gupta** [feder-cr/linkedIn_auto_jobs_applier_with_AI#381]
The package installation fails due to conflict of package versions.

below is the actual error.

---------------------------------------------------------------------------------------------------------------------------------------------------
INFO: pip is looking at multiple versions of langchain-ollama to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r .\requirements.txt (line 1), -r .\requirements.txt (line 18), -r .\requirements.txt (line 2), -r .\requirements.txt (line 4), -r .\requirements.txt (line 5) and langchain-core==0.2.24 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested langchain-core==0.2.24
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------------------------------------------------------------------------------------------------------------------------------------------

Is it a good idea to just remove versions in the requirments.txt or try look for compatable version.

I am using a windows machine with python 3.12.4 and pip 24.2 version.

**Comment by sai-rohit-gupta** [comment]
I found some similar discuession of the package dependency on a different issue's comment which leads to v3's pull where it says to be resolved by changing some versions.


Check out #353

**Comment by sai-rohit-gupta** [comment]
Please close this when the issue is resolved and tested.

**Comment by thomHayner** [comment]
@sai-rohit-gupta remove all dependency versions from affected packages and rerun pip install.

your file will look something like this:
```
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
langchain
langchain-anthropic
langchain-community
langchain-core
langchain-google-genai
langchain-ollama
langchain-openai
langchain-text-splitters
langsmith==0.1.93
Levenshtein==0.25.1
```
Your file may not be an exact copy of the above code, this is only meant to illustrate the point...if you get console errors just keep removing versions from affected dependencies until pip resolves a valid configuration.

**Comment by sai-rohit-gupta** [comment]
Thanks for the response. I figured this out. But someone has to create a PR to resolve this. I.e When some user uses it, It has to work right out of the box. Hence keeping this to be a good beginner/starter contribution to be resolved.!!!!

**Comment by feder-cr** [comment]
@sai-rohit-gupta join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
