### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by sdhanwani** [feder-cr/linkedIn_auto_jobs_applier_with_AI#382]
Hello,I am new to git and python so don't have much knowledge about it, I was trying to edit in virtual folder to comment the package/code however when I expanded it, I couldn't find it. Can you please guide me through it please?

![image](https://github.com/user-attachments/assets/05687813-beb4-42ed-8a74-be1b69b08c52)

**Comment by thomHayner** [comment]
@sdhanwani the virtual is created programmatically by the software...you will need to activate the virtual environment before the program will create the folder.

When you complete [steps 4 and 5 of the  **Installation** instructions section in README.md](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/main/README.md#installation), the ```virtual/``` folder should be created locally on your device.

https://t.me/AIhawkCommunity

**Comment by sdhanwani** [comment]
Can you please give the command that activates virtual environment on windows

**Comment by thomHayner** [comment]
@sdhanwani 

> ... complete [steps 4 and 5 of the **Installation** instructions section in README.md](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/main/README.md#installation), the `virtual/` folder should be created ...

**Comment by feder-cr** [comment]
@sdhanwani @mmcc007 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
