### ISSUE TITLE
ERROR: Package 'lib-resume-builder-aihawk' requires a different Python: 3.9.0 not in '>=3.10'

### ISSUE THREAD

**Issue by Pranil51** [feder-cr/linkedIn_auto_jobs_applier_with_AI#384]
When I tried to install packages in the requirements.txt file, I got this error. I tried both with conda as well as this pytho enironment on my windows.

**Comment by feder-cr** [comment]
@Pranil51    Try now

**Comment by Pranil51** [comment]
@feder-cr It's working now

**Comment by feder-cr** [comment]
@Pranil51 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
