### ISSUE TITLE
Please stop spamming external communities.

### ISSUE THREAD

**Issue by ilulillirillion** [feder-cr/linkedIn_auto_jobs_applier_with_AI#387]
https://www.reddit.com/user/AIHawk_Founder/

I've forwarded the account with a report to github admins regarding spam coming from this project. If this user is not affiliated with your project, you should contact Reddit. Please stop spamming your project in communities where you know full well it is not appropriate to do so. It's a shame that this is the face you choose to attach to your project.

**Comment by DrakeRichards** [comment]
This looks like it *would* be an interesting project on its own, but the frequent spamming is incredibly suspicious. There was also an [unnatural spike in stars from August 27th to August 31st](https://star-history.com/#feder-cr/linkedIn_auto_jobs_applier_with_AI&Date), after which the project resumed its pre-spike growth rate. That looks like botted activity.

**Comment by ilulillirillion** [comment]
Some comments from others on the posts being made (some of them are quite angry, understandably, and I don't want to share them here due to profanity):

> [u/AIHawk_Founder](https://www.reddit.com/user/AIHawk_Founder/) should be banned for spamming. Reported.

> I banned this guy earlier today in another sub! It’s been hours, I’m surprised the account can still post at this point.

> I’ve submitted about 60 reports to Reddit. 

> I reported his repo to github

> Yeah, I reported a ton myself.

> Reported about 2 dozen posts, and also reported their spamming to the Github account linked.

> I think I’m at 80-100 reports. I’ve been following them/it and shutting down posts. 

There are many more, but I don't want to belabor the point. I think this project is promising and I don't hold any ill will towards the contributors themselves, but I want to make it clear that this behavior is affecting a broad range of communities and has not been appreciated.

**Comment by smatian** [comment]
I am extremely confused on what the prime motive is to this mass marketing for this project. It's an open source simple python script, why is he advertising it so much? He's not making any money unless he hoping for a sponsorship or something

**Comment by ralyodio** [comment]
What spam? People post projects on Reddit and HN all the time.

**Comment by ilulillirillion** [comment]
> What spam? People post projects on Reddit and HN all the time.

In the past 2 hours, that account, claiming to be the owner of this repository, alone, has created at least 102 posts in separate communities about this project, all generated with some type of template and maybe AI to mix it around.

I say at least because this has been going on for much longer than that, but I am no longer even able to go back further in the post history than that.

The vast majority (nearly all) of these posts are removed by moderators within less than 5 minutes. It is absolutely excessive and unwanted spam.

**Comment by feder-cr** [comment]
@ilulillirillion @DrakeRichards @smatian As the creator of the project, I want to clarify that we cannot be held responsible for any actions taken by third parties with the intent to undermine or disregard our work. Furthermore, I find it absurd to flag a project simply because an unidentified individual is spamming it, as it is beyond our control to identify or manage such behavior.

**Comment by ilulillirillion** [comment]
@feder-cr  Are you denying that the account claiming in hundreds of posts to be you and representing your project, is you? Nor does it concern you in any way?

**Comment by tomeknd** [comment]
> What spam? People post projects on Reddit and HN all the time.

The issue is not that the project is posted on relevant subreddits, it's that it's being spammed all over the place (Battlefield V, OkCupid (lmao), French, HalfLife subreddits, to name a few) and OP uses disingenuous claims with no evidence to push it.

**Comment by tomeknd** [comment]
> @ilulillirillion @DrakeRichards @smatian As the creator of the project, I want to clarify that we cannot be held responsible for any actions taken by third parties with the intent to undermine or disregard our work. Furthermore, I find it absurd to flag a project simply because an unidentified individual is spamming it, as it is beyond our control to identify or manage such behavior.

If this person is not affiliated with the project then it should be in _your_ best interest to make them stop because they're making you look extremely bad.

**Comment by ralyodio** [comment]
I don't think its us, we get a ton of people using this project. Its certainly not me. I shared it on HN once.
