### ISSUE TITLE
remote error in config.yaml file

### ISSUE THREAD

**Issue by olufamilusi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#4]
This is the error I keep getting after running through the config,yaml file and when I look through the main.py file, nothing there seems absurd. Anyone able to help?

PS D:\LinkedinAI-Bot\LinkedIn_AIHawk_automatic_job_application> python main.py
Configuration error: 'remote' in config file data_folder\config.yaml must be a boolean value.

**Comment by feder-cr** [comment]
please share your config.yaml

**Comment by olufamilusi** [comment]
remote: true
experienceLevel:
 internship: false
 entry: false
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: true
 month: false
 week: true
 24 hours: false

positions:
  - Linux Engineer

locations:
  - Country1
  - Country2

distance: 100

companyBlacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2

**Comment by olufamilusi** [comment]
Done everything I can but it isnt working yet

**Comment by olufamilusi** [comment]
> please share your config.yaml

Thank yo! Thank you! I got it to work!! Thank you for sharing this!!

**Comment by azjz92** [comment]
what was the fix??? currently suffering this

**Comment by olufamilusi** [comment]
I used chatGPT alot in trying to fix any and all issues I had. There is also something you must know if you dont already know. When you use this code, it applies for you based on the job description of the jobs it finds, if you dont have a specific resume that you ask it to use. I didnt and it applied for "easy apply" jobs for me but most of which I had no experience for, so that's something to watch out for!

**Comment by azjz92** [comment]
Ok I'm thinking it's something silly with my set up, do you mind opening
this issue again, I will post the solution when I find it to hopefully help
others down the line ! Thx :)

On Tuesday, August 20, 2024, olufamilusi ***@***.***> wrote:
> I honestly cant remember the specific fix becuase I was frustrated myself
and was just copying/pasting using gpt at some point but if this helps,
this is what my config.yml file looks after some tweaking.
>
> remote: true
> experienceLevel:
> internship: false
> entry: false
> associate: true
> mid-senior level: true
> director: false
> executive: false
>
> jobTypes:
> full-time: true
> contract: true
> part-time: true
> temporary: false
> internship: false
> other: false
> volunteer: false
>
> date:
> all time: true
> month: false
> week: true
> 24 hours: false
>
> positions:
>
> Linux System Engineer
> Linux System Administrator
> IT System Administrator
>
> locations:
>
> Dallas, TX
> United States
>
> distance: 100
>
> companyBlacklist:
>
> Company1
> Company2
>
> titleBlacklist:
>
> Sales
> Marketing
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci3.googleusercontent.com/meips/ADKq_Nb-wpd-gg6kuZjXwb6F8jBuO-bB762P8wmYOq-yxLtDFlM6nFyGrn1OfJqAGE9WQ3ke6ZymM1Yg9HQuk13FEU6o44eVRHqdiMQNn8J0Cco2aOyS9sonF6J1xGonKhSYIbOuNLJTEGA64AYeAlwdKvrvRc_8SLlR1ypkUATJO2EnRHqrQ6T3LJkorzK7cp-_Z_hLdfgwu-ctqKNCKpc-n6pGRNCSxAmjxZmhDNUQ-9cNpo2ywWnmLZo=s0-d-e1-ft#https://github.com/notifications/beacon/ANWK5AO2VHWO4CZ5QANMILTZSM4P3A5CNFSM6AAAAABMKGK2MCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUJATSZI.gif>Message
ID: <feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/4/
***@***.***>

**Comment by GregFree** [comment]
I'm having the same "remote" issue when trying to initialize. I changed my .yaml to match that  with the poster above. Both version run into the same problem.

![image](https://github.com/user-attachments/assets/a935ff84-a1c2-46fd-a404-cabb74a01721)

**Comment by madhuptiwari** [comment]
I solved this problem. This **problem was related to indentation**. Once your **indentation** in file is same as that of files in data_folder_example. You'll be able to run it. Hope this helps.

If in case you get a runtime error. That will be due to a parsing error in one of YAML files. I think most people will make errors in resume.yaml file.

Note: Check your code or opening and closing braces.
