### ISSUE TITLE
Code not executing 

### ISSUE THREAD

**Issue by sitharavs** [feder-cr/linkedIn_auto_jobs_applier_with_AI#409]
C:\path>cd C:\path\Documents\Automate Job Applications\linkedIn_auto_jobs_applier_with_AI

C:\path\Documents\Automate Job Applications\linkedIn_auto_jobs_applier_with_AI>python -m venv .venv

C:\path\Documents\Automate Job Applications\linkedIn_auto_jobs_applier_with_AI>$ python -m venv .venv
'$' is not recognized as an internal or external command,
operable program or batch file.

C:\path\Documents\Automate Job Applications\linkedIn_auto_jobs_applier_with_AI>python -m venv .venv

C:\path\Documents\Automate Job Applications\linkedIn_auto_jobs_applier_with_AI>.venv\Scripts\activate.bat

(.venv) C:\path\Documents\Automate Job Applications\linkedIn_auto_jobs_applier_with_AI>python main.py --resume My name - Resume.pdf

(.venv) C:\path\Documents\Automate Job Applications\linkedIn_auto_jobs_applier_with_AI>

My notes - 
this is what I tried to run, please tell me if I have missed anything or gone wrong somewhere. However, my code is not executing

**Comment by sitharavs** [comment]
@pancho-villa , I did that step during installing.
Virtual Env got disconnnected
hence I did these steps 

Please let me know how to fix the issue if you have any idea

**Comment by feder-cr** [comment]
@pancho-villa please follow the readme! join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
