### ISSUE TITLE
[Feat] Move secrets

### ISSUE THREAD

**Issue by ungaratto93** [feder-cr/linkedIn_auto_jobs_applier_with_AI#44]
Why secrets data cannot be in env vars ? In my opinion the actual state is a bad practice

**Comment by feder-cr** [comment]
hello, it becomes too complicated for users, just pay a little attention!
  @ungaratto93 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by ralyodio** [comment]
i agree, username and pass should be in `.env` and ignored in `.gitignore`

**Comment by ungaratto93** [comment]
Keep in your mind that IS not hard setup .env file
