### ISSUE TITLE
GitHub please delete this repo and ban this guy. He is using bots to increase his star count artificially and is spaming reddit to promote this garbage. 

### ISSUE THREAD

**Issue by adam-mcdonald** [feder-cr/linkedIn_auto_jobs_applier_with_AI#48]

**Comment by feder-cr** [comment]
Important Announcement Regarding My Repository 

Hello everyone,

I wanted to bring an important issue to your attention regarding my GitHub repository, [linkedIn_auto_jobs_applier_with_AI](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI). Recently, my project has been targeted by a malicious campaign. Someone has artificially inflated the number of stars on my repository and is now spreading false accusations that I have purchased fake stars.

This campaign appears to be an attempt to damage my reputation and possibly get my repository banned from GitHub. I want to make it very clear that I have not engaged in any dishonest practices, and I am working to address this issue with GitHub's support team.

If you see any misleading information being spread about my repository, please know that it is false. I greatly appreciate the support of the community and will continue to work on providing valuable tools through my project.

Thank you for your understanding and support.

Best regards,
feder-cr

**Comment by adam-mcdonald** [comment]
Lol nice chatgpt response buddy...You can clearly see based on your past posts that you're not a native English speaker. You're not fooling anyone with these lies.

**Comment by HassDhia** [comment]
I've been using the program and it's great. Even if english isn't his first language, the repo works and the telegram group is supportive. Not sure what troll comment above is on about.

**Comment by adam-mcdonald** [comment]
He is using bots to manipulate the star count on this repo, which is against the terms of service for GitHub. You may think that's not a big deal, but it falsy gives credibility to his work, which can steer someone into blindly using it. He's also using bots to spam Reddit. 

I have nothing against him not being a native English speaker. My response was regarding his comment stating that someone is 'trolling' him and using bots to artificially increase the repo star count. Not only was this response written entirely with GPT, but the idea that someone would do so is hilarious. Just own up to the fact that he's using deceptive practices to adopt users.

**Comment by adam-mcdonald** [comment]
> I've been using the program and it's great. Even if english isn't his first language, the repo works and the telegram group is supportive. Not sure what troll comment above is on about. 

He is using bots to manipulate the star count on this repo, which is against the terms of service for GitHub. You may think that's not a big deal, but it falsy gives credibility to his work, which can steer someone into blindly using it. He's also using bots to spam Reddit. 

I have nothing against him not being a native English speaker. My response was regarding his comment stating that someone is 'trolling' him and using bots to artificially increase the repo star count. Not only was this response written entirely with GPT, but the idea that someone would do so is hilarious. Just own up to the fact that he's using deceptive practices to adopt users.

**Comment by feder-cr** [comment]
@adam-mcdonald hello, i am not using any bot to increase my stars, there are several tools on github that can help you to analyze my star flow and see that it is regular, yours is a full blown defamation

**Comment by adam-mcdonald** [comment]
> @adam-mcdonald hello, i am not using any bot to increase my stars, there are several tools on github that can help you to analyze my star flow and see that it is regular, yours is a full blown defamation

Ok, bud. The fact that the majority of your stars have come from accounts created in the last month with no other activity is not suspicious at all....GitHub has already received multiple reports, so I guess we'll see what they think after they've evaluated everything. If GitHub reports back everything is legit I'll happily eat my words and provide an apology. I doubt that will happen though.

**Comment by feder-cr** [comment]
@adam-mcdonald  there are several tools to analyze stars, they turn out to be stars with new accounts only 300, out of about 3000, I don't understand where the problem is, if not your strong envy

**Comment by adam-mcdonald** [comment]
> @adam-mcdonald there are several tools to analyze stars, they turn out to be stars with new accounts only 300, out of about 3000, I don't understand where the problem is, if not your strong envy

I am not envious. As I mentioned above, the idea that you received 3000 legitimate stars within 7 days is highly unlikely. I'm not the only one that believes so. Go check all the subreddits your bot spammed yesterday. Comments were almost exclusively negative with skeptics. 

GitHub has already responded to me that they're evaluating your repo. If it passes their check I will absolutely admit I was wrong.

**Comment by feder-cr** [comment]
@adam-mcdonald I don't care about the comments, I'm helping a lot of people and I'm creating a huge community, that's more than okay with me, of course you're going to be sued for this defamation without any evidence, which affects my person directly and my professionalism

**Comment by adam-mcdonald** [comment]
Bwahahaha. Ok bud. Sue away. I'm sure my comments have lost you millions of dollars of potential revenue. Please make sure to send me your chatGPT written cease and desist as soon as possible so I can have a good laugh.
