### ISSUE TITLE
FileManager def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) 

### ISSUE THREAD

**Issue by Neojin629** [feder-cr/linkedIn_auto_jobs_applier_with_AI#51]
Hello, running into the following issue when running the bot:

`Traceback (most recent call last):
  File "/Users/user/AI Application Tool/linkedIn_auto_jobs_applier_with_AI/main.py", line 120, in <module>
    class FileManager:
  File "/Users/user/AI Application Tool/linkedIn_auto_jobs_applier_with_AI/main.py", line 151, in FileManager
    def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) -> dict:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`

Not sure why this is happening.  The file that the file manager is attempting to find is there.  

Currently running it on a M1 Mac.  

Thanks.

**Comment by Neojin629** [comment]
solution find! python3.9 is not supported | , so please specify in readme please! supported for 3.10 and +

**Comment by EdCordata** [comment]
Solution is to import replace in `main.py` this:

```python
def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) -> dict:
```
to this:
```python
def file_paths_to_dict(resume_file: Union[Path, None], plain_text_resume_file: Path) -> dict:
```

Note that you also have to import `Union` at the top of the file:
```python
from typing import Union
```
