### ISSUE TITLE
The code is applying to same job multiple times

### ISSUE THREAD

**Issue by abhishekchemistry** [feder-cr/linkedIn_auto_jobs_applier_with_AI#54]
Hi! First of all, it's an amazing tool and thanks a lot for making life easy for job seeking people.

I just checked the output/success.csv file and the bot is applying multiple times to a single job. Please let me know how it can be fixed. A screenshot is attached.
![Screenshot from 2024-08-19 17-48-00](https://github.com/user-attachments/assets/0e125c23-68ec-40c3-b54e-8c8ca333d99a)

**Comment by feder-cr** [comment]
It s a simple bug in the logs, you can't apply it multiple times for the same job!

join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by feder-cr** [comment]
@abhishekchemistry

**Comment by abhishekchemistry** [comment]
@feder-cr thank you very much. :)
