### ISSUE TITLE
Handshake Failed and Tailored Resume Failure

### ISSUE THREAD

**Issue by aditya-kanala** [feder-cr/linkedIn_auto_jobs_applier_with_AI#55]
Hello, 
Firstly thank you so much for giving us such a useful product and helping us. I have been using it for the last 4 days and running into a couple of issues.

1. When I start the bot in my Windows system, it says handshake failed and an SSL error. So I tried switching to Brave Browser and now it runs fine but sometimes the same issue occurs. However, this is not blocking the bot's functionality and the bot can still submit the applications.
2.  How many ever times I clone the repo, the tailored resume is not getting generated and the generated_cv folder remains the same all the time The applications are getting submitted with my last used resume
3. Once the application is submitted, I think it encounters some exceptions sometimes and sleeps for around 10 minutes before going on to the next application, and sometimes it just aborts.

**Comment by feder-cr** [comment]
@aditya-kanala Hi, ignore SSL issues; they are simple warnings, timeouts are inserted to limit the power of the bot and avoid any bans.
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
