### ISSUE TITLE
Still some questions about the config.yaml file 

### ISSUE THREAD

**Issue by olufamilusi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#56]
> please share your config.yaml

Thank yo! Thank you! I got it to work!! Thank you for sharing this!!

_Originally posted by @olufamilusi in https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/4#issuecomment-2282362574_

**Comment by azjz92** [comment]
v2 solved this, along with not being a fool and making sure chrome was installed! 💯 🥇

**Comment by ralyodio** [comment]
DId v2 merge to main yet?

**Comment by feder-cr** [comment]
@ralyodio yep
