### ISSUE TITLE
Suggested GPT model?

### ISSUE THREAD

**Issue by retropele** [feder-cr/linkedIn_auto_jobs_applier_with_AI#57]
Hey, thanks for your work.

What model is this designed to work with? I'm not very familiar with open ai.

**Comment by azjz92** [comment]
Hey, all you need to do is create a secret api key on open ai, check the readme, it takes a couple minutes. then paste that api key into the relevant secrets.yaml file. I think you have to pay for token access though for it to work but it should be very cheap. I'm still figuring things out.

**Comment by retropele** [comment]
No probs, what I'm asking is which gpt model e.g. 4, turbo or whatever?

**Comment by feder-cr** [comment]
Bro, the bot automatically use 4o-mini, join in our telegram group, https://t.me/AIhawkCommunity

@azjz92 @retropele @snithercode @Thepathakarpit
