### ISSUE TITLE
Not all config is always followed

### ISSUE THREAD

**Issue by kevin-v96** [feder-cr/linkedIn_auto_jobs_applier_with_AI#6]
First of all, thank you so much for the great project! I used it to automate a task I dreaded doing every day, and overall it works great.

Sometimes I see it ignoring explicit configurations, like applying to jobs that are weeks old when only 24 hours ago is true, or applying for roles with titles in the titleBlacklist. If you want, I could try to screenrecord to provide examples, but I'd love to contribute in solving this issue!

**Comment by feder-cr** [comment]
hello, yes of course, let me if you find bugs please report them all and in as much detail as possible, for now it's just me working on it, but I will do everything to fix them as soon as possible

**Comment by feder-cr** [comment]
@kevin-v96

**Comment by feder-cr** [comment]
@kevin-v96 solved?
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by kevin-v96** [comment]
Hey @feder-cr , sorry I couldn't get back earlier, been a little busy. Will join the telegram channel and talk more about this.
