### ISSUE TITLE
City requires autofill

### ISSUE THREAD

**Issue by SpaceshipxDev** [feder-cr/linkedIn_auto_jobs_applier_with_AI#64]
LinkedIn requires autofill for the city input - 4o mini simply enters 'Melbourne', but LinkedIn requires 'Melbourne, Victoria, Australia'

**Comment by feder-cr** [comment]
i know, i will fix.
@SpaceshipxDev join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
