### ISSUE TITLE
   Create your resume style in CSS

### ISSUE THREAD

**Issue by scottiesan** [feder-cr/linkedIn_auto_jobs_applier_with_AI#67]
Any idea what this is referring to?

Getting this when running main.py

[?] Which style would you like to adopt?: Default (style author -> https://github.com/krishnavalliappan)
 > Default (style author -> https://github.com/krishnavalliappan)
   Create your resume style in CSS

Thanks!

**Comment by feder-cr** [comment]
sorry i dont understand, you can follow this guide for propouse a new css style->https://github.com/feder-cr/lib_resume_builder_AIHawk/blob/main/how_to_contribute/web_designer.md

**Comment by feder-cr** [comment]
@scottiesan join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
