### ISSUE TITLE
Allow for local llm or ollama support?

### ISSUE THREAD

**Issue by devlux76** [feder-cr/linkedIn_auto_jobs_applier_with_AI#68]
Excellent project. I haven't looked at the code yet, but I'm willing to bet I could get ollama or some other local llm working with it. 

If I can get it going would you be interested in a PR?

**Comment by feder-cr** [comment]
Yes but, we this need to be easy for the final user

**Comment by feder-cr** [comment]
@devlux76  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
