### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by SatyaProgramming** [feder-cr/linkedIn_auto_jobs_applier_with_AI#70]
Runtime error: Error running the bot: AttributeError in experience_details processing: AttributeError in Experience: 'str' object has no attribute 'values'
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

**Comment by feder-cr** [comment]
Follow the data_folder_example

**Comment by SatyaProgramming** [comment]
i can't find out exactly what's wrong
remote: true  # Set to true for remote jobs, false otherwise  

experienceLevel:  
  internship: false     # For internship positions  
  entry: true           # For entry-level positions  
  associate: true      # For associate-level positions  
  mid-senior level: false # For mid-level positions (changed space to underscore)  
  senior: false         # For senior-level positions  
  director: false  
  executive: false  

jobTypes:  
  full-time: true       # Changed to underscore for consistency  
  part-time: false  
  contract: false
  part-time: false
  temporary: false
  internship: true
  other: false
  volunteer: false 

date:  
  all time: false
  month: true
  week: true
  24 hours: true 

positions:  
  - "Java Developer"  
  - "Spring Boot Developer"  
  - "Software Developer"  
  - "Backend Developer"  
  - "Java Spring Boot Developer"  

locations:  
  - "India"  
  - "Hyderabad"  
  - "Bangalore"  
  - "Chennai"  
  - "Pune"  

distance: 50  # Distance in miles  

companyBlacklist:  
  - "Noir" 
  - "Company Y"  

titleBlacklist:  
  - "Sales"  
  - "Marketing"

**Comment by neo-con** [comment]
@SatyaProgramming 

I think the error is coming from your 'resume' file not the 'config' file. 


You should paste what you got here:

experience_details:
  - position: "[Your Job Title]"
    company: "[Company Name]"
    employment_period: "[Start Date] - [End Date]"
    location: "[Location]"
    industry: "[Industry]"
    key_responsibilities:
      - responsibility_1: "[Key Responsibility 1]"
      - responsibility_2: "[Key Responsibility 2]"
      - responsibility_3: "[Key Responsibility 3]"
    skills_acquired:
      - "[Skill 1]"
      - "[Skill 2]"
      - "[Skill 3]"

**Comment by SatyaProgramming** [comment]
No there is no mistakes
personal_information:
  name: "---"
  surname: "----"
  date_of_birth: "01/04/2001"
  country: "India"
  city: "Hyderabad"
  address: "Begumpet"
  phone_prefix: "+91"
  phone: "---"
  email: "---"
  github: "https://github.com/SatyaProgramming"
  linkedin: "---"

education_details:
  - degree: "Master of Computer Application"
    university: "Biju Patnaik University of Technology"
    gpa: "8.42/10"
    graduation_year: "2023"
    field_of_study: "Software Engineering"
    exam:
      Algorithms: "A"
      Data Structures: "B+"
      Database Systems: "A"

experience_details:
  - position: "Software Developer"
    company: "Microden Software Solutions."
    employment_period: "06/2023 - 08/2024"
    location: "Begumpet, Hyderabad"
    industry: "Technology"
    key_responsibilities:
      - "Developed web applications using React and Java"
      - "Collaborated with cross-functional teams to design and implement new features"
      - "Troubleshot and resolved complex software issues"
    skills_acquired:
      - "React"
      - "Java"
      - "Software Troubleshooting"

projects:
  - name: "Online Banking App"
    description: "A web application that provides real-time loan information using a third-party API."
    link: "https://github.com/"

achievements:
  - name: "Employee of the Month"
    description: "Recognized for exceptional performance and contributions to the team."

certifications:
  - "Certified Java Developer"
  - "Spring Boot Developer"

languages:
  - language: "Hindi"
    proficiency: "Fluent"
  - language: "English"
    proficiency: "Intermediate"

interests:
  - "Developer"
  - "SPring Boot"

availability:
  notice_period: "2 weeks"

salary_expectations:
  salary_range_usd: "1430.76 - 11923" # Example range, adjust based on your expectations

self_identification:
  gender: "Male"
  pronouns: "He/Him"
  veteran: "No"
  disability: "No"
  ethnicity: "Asian"

legal_authorization:
  eu_work_authorization: "No" # Not applicable
  us_work_authorization: "No" # Not applicable
  requires_us_visa: "No" # Not applicable
  requires_us_sponsorship: "No" # Not applicable
  requires_eu_visa: "No" # Not applicable
  legally_allowed_to_work_in_eu: "No" # Not applicable
  legally_allowed_to_work_in_us: "No" # Not applicable
  requires_eu_sponsorship: "No" # Not applicable
  


work_preferences:
  remote_work: "Yes"
  in_person_work: "No"
  open_to_relocation: "Yes"
  willing_to_complete_assessments: "Yes"
  willing_to_undergo_drug_tests: "No" # Not typically required in India
  willing_to_undergo_background_checks: "Yes"

**Comment by SatyaProgramming** [comment]
Thanks

**Comment by SatyaProgramming** [comment]
![image](https://github.com/user-attachments/assets/b76960e5-801c-4926-af4f-9cd73a8d259e)

**Comment by dmartin4820** [comment]
@SatyaProgramming Looks like you need to add credits on your OpenAI account. https://platform.openai.com/settings/organization/billing
