### ISSUE TITLE
Bot not aplying to any job also adding wrong location and filter  and many other issues

### ISSUE THREAD

**Issue by waqaramjad** [feder-cr/linkedIn_auto_jobs_applier_with_AI#72]
### **Issues:** 

system: MacOS

- Not applying to job car
- Wrong location on linked sararch filter 
- if pre login than give error 
- if logout but linked giving profile icon to login it not works in tihs case 

**For location:** 

For example if i enter USA it will search inside city of linkedin like baltimore,usa same for othe search filters 

**For applying:**
When it open job list it only tap first one if already applied than just start scrolling other list and not applying and goes to sleep

**Comment by mohamed2m2018** [comment]
I have same issue on macos

**Comment by feder-cr** [comment]
I hope someone in the future can fix this!

**Comment by kanlanc** [comment]
Got the same issue, any fixes?
