### ISSUE TITLE
Canada work authorization?

### ISSUE THREAD

**Issue by BovineOverlord** [feder-cr/linkedIn_auto_jobs_applier_with_AI#76]
I'm applying for jobs in Canada, however there is no equivalent to a "us_work_authorization" line in the plain txt resume file for Canada. Would you be able to add this? Meanwhile, in the short term, would manually adding a "canada_work_authorization" line suffice to add this check?

**Comment by feder-cr** [comment]
Why on plain text? Do you mean on config?

**Comment by BovineOverlord** [comment]
Yes

**Comment by Alisa-Mak** [comment]
so can I manually add the following to linkedIn_auto_jobs_applier_with_AI/tree/main/src/job_application_profile.py
and then use the corresponding fields in data_folder_example/plain_text_resume.yaml file?
    
```
    # Adding Canada-specific attributes based on typical requirements
    canada_work_authorization: str  # e.g., "Yes" or "No"
    requires_canadian_visa: str  # e.g., "Yes" or "No"
    legally_allowed_to_work_in_canada: str  # e.g., "Yes" or "No"
    requires_canadian_sponsorship: str  # e.g., "Yes" or "No"
```

**Comment by josylad** [comment]
> so can I manually add the following to linkedIn_auto_jobs_applier_with_AI/tree/main/src/job_application_profile.py and then use the corresponding fields in data_folder_example/plain_text_resume.yaml file?
> 
> ```
>     # Adding Canada-specific attributes based on typical requirements
>     canada_work_authorization: str  # e.g., "Yes" or "No"
>     requires_canadian_visa: str  # e.g., "Yes" or "No"
>     legally_allowed_to_work_in_canada: str  # e.g., "Yes" or "No"
>     requires_canadian_sponsorship: str  # e.g., "Yes" or "No"
> ```

for selenium to find those fields, you need to check the field ID or class on LinkedIn and set the appropriate values.
