### ISSUE TITLE
already logged

### ISSUE THREAD

**Issue by us** [feder-cr/linkedIn_auto_jobs_applier_with_AI#8]
when i logged in already in chromedriver, it goes to /feed page directly, but bot still looks for login page! 

Starting Chrome browser to log in to LinkedIn.
Navigating to the LinkedIn login page...
Login form not found. Aborting login.
Login button not found. Please verify the page structure

**Comment by feder-cr** [comment]
wait 30 seconds, need to implement 2fa management, when I do this bug will no longer exist @us
