### ISSUE TITLE
Best way to get banned your account

### ISSUE THREAD

**Issue by imran-khani** [feder-cr/linkedIn_auto_jobs_applier_with_AI#81]
Linkedin recently banned accounts for using third party apps.

**Comment by Yashground** [comment]
I had this doubt as well, maybe if we use Linked.in/developer or limit the selenium/scraping function to mimic human like behaviour and limit scraping ?

**Comment by feder-cr** [comment]
I don't know anyone who has ever been banned! @imran-khani @Yashground
