### ISSUE TITLE
Make some fields optional

### ISSUE THREAD

**Issue by Udomaki** [feder-cr/linkedIn_auto_jobs_applier_with_AI#84]
Hello, Love the project and have a couple of suggestions:

1. make education optional
2. make github link optional

Appreciate the consideration!

**Comment by datnodude** [comment]
I agree fields such as gpa and projects would be nice to be optional.

**Comment by Zanuah** [comment]
Need this.  A lot of the sections are pointless.  Most of them are.  To make this work I have to hack up the code or put in dummy nonsense.

**Comment by feder-cr** [comment]
good idea
@Zanuah @datnodude @Udomaki join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
