### ISSUE TITLE
Binary Error

### ISSUE THREAD

**Issue by DPancholi7** [feder-cr/linkedIn_auto_jobs_applier_with_AI#86]
Runtime error: Error running the bot: Failed to initialize browser: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x629c8df7f4e3 <unknown>
#1 0x629c8dcaec76 <unknown>
#2 0x629c8dcd5757 <unknown>
#3 0x629c8dcd4029 <unknown>
#4 0x629c8dd12ccc <unknown>
#5 0x629c8dd1247f <unknown>
#6 0x629c8dd09de3 <unknown>
#7 0x629c8dcdf2dd <unknown>
#8 0x629c8dce034e <unknown>
#9 0x629c8df3f3e4 <unknown>
#10 0x629c8df433d7 <unknown>
#11 0x629c8df4db20 <unknown>
#12 0x629c8df44023 <unknown>
#13 0x629c8df121aa <unknown>
#14 0x629c8df686b8 <unknown>
#15 0x629c8df68847 <unknown>
#16 0x629c8df78243 <unknown>
#17 0x74bddf759609 start_thread

**Comment by feder-cr** [comment]
try to:

 1) unistall chromedriver

 2) unistalll chrome

3) unistall python

 3) delete folder C:\Users[Your Username]\AppData\Local\Google

 4) delete folder google-chrome on the project

 5) Reinstall chrome

 6) Follow the readme(install last python version)

@DPancholi7 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
