### ISSUE TITLE
Runtime error: Error running the bot: Error parsing YAML file.

### ISSUE THREAD

**Issue by Securitydude3245** [feder-cr/linkedIn_auto_jobs_applier_with_AI#89]
Good afternoon! I went through all the steps and have matched my files to your example files and I am getting an error:
Runtime error: Error running the bot: Error parsing YAML file.
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration
when I run the python main.py command. I have run the YAML's through a validator and do not have any great feedback there. I have also run line by line through the text and it matches so I am not sure what the issue is.

**Comment by rajatsing** [comment]
exact same error for me

**Comment by Jarne-Banane** [comment]
Try adding responsibilty_1, responsibility_2 ... before every responsibility. for every position. solved it for me :) i needed an hour to figure it out
![Screenshot 2024-08-27 212249](https://github.com/user-attachments/assets/16b1ff1b-6a11-4abd-8479-872f4be149e9)

**Comment by Securitydude3245** [comment]
Yes mine is setup that way already.

**Comment by Dmorok** [comment]
same here

**Comment by Aravind101999** [comment]
> Try adding responsibilty_1, responsibility_2 ... before every responsibility. for every position. solved it for me :) i needed an hour to figure it out ![Screenshot 2024-08-27 212249](https://private-user-images.githubusercontent.com/173855857/362097585-16b1ff1b-6a11-4abd-8479-872f4be149e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODY5MzAsIm5iZiI6MTcyNDg4NjYzMCwicGF0aCI6Ii8xNzM4NTU4NTcvMzYyMDk3NTg1LTE2YjFmZjFiLTZhMTEtNGFiZC04NDc5LTg3MmY0YmUxNDllOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQyMzEwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjM5ZGE4NWEwZTA3MWUwMDE0NTNkNDNmNjkwNmU3MjI0YWQyOGExOGZmODQzZjZiNTk1ZjM5ODMwYTQxMWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8miSPJvZaFUY4usyzAkQ2zXvkQaBAQ61MMkHdgSvRzw)

__

**Comment by Dmorok** [comment]
still not fixed, redownloaded and tried with demo file - same error

**Comment by happyn-07** [comment]
Same error. I have checked all the files for errors. Redid the entire process twice. Not yet fixed

**Comment by earl562** [comment]
did you guys try pip installing yaml?

**Comment by happyn-07** [comment]
Finally solved it. I used a bot of an unorthodox approach but it worked. I commented out all the lines of code by selecting all and pressing cmd+/. I noticed that some lines didn't get commented out. I rewrote all those lines that didn't comment out. That fixed it for me.

I used vs code.

**Comment by Carl0-C0des** [comment]
To help resolve the YAML parsing issue you're encountering, I noticed from the screenshot that the responsibilities are structured as separate keys like responsibility_1, responsibility_2, etc. While this structure might look correct, the issue likely stems from the YAML format expecting a list under a single key instead of multiple numbered keys.

Here’s how you can fix it:

Instead of:

```
key_responsibilities:
  - responsibility_1: "Managed projects..."
  - responsibility_2: "Led teams..."
```
  
_**You should structure it as**_:

```
key_responsibilities:
  - description: "Managed projects..."
  - description: "Led teams..."
```
  
So each responsibility is just an item in the list under the description key, as this is a standard YAML list structure. Additionally, make sure all your indentation is consistent (2 spaces is typical), and validate again with your tool. This should solve the parsing error.

**Comment by shaan1991** [comment]
resumes are being geenrated with zero bytes - can someone help me with this please?

**Comment by max870701** [comment]
This program keeps generated resumes with zero bytes. Is there any solution?

**Comment by AAdemide** [comment]
Hey, I had the same issue and the problem happened because the description of my projects was too long after shortening it it worked.
