### ISSUE TITLE
Nothing happens/No Output when running resume path, I get nothing in terminal after running python main.py / resume path, and if i just run python main.py i get the stupid "Configuration error: Invalid type for key 'remote' in config file data_folder\config.yaml. Expected <class 'bool'>.

### ISSUE THREAD

**Issue by azjz92** [feder-cr/linkedIn_auto_jobs_applier_with_AI#90]
I get nothing in terminal after running python main.py / resume path, and if i just run python main.py i get the stupid "Configuration error: Invalid type for key 'remote' in config file data_folder\config.yaml. Expected <class 'bool'>.
" even with true for that spot, attached a pdf, also thanks for the awesome work! 
![image](https://user-images.githubusercontent.com/57454209/361935269-8a6f6724-352f-4e35-9337-0aeb631163d4.png)
, in v2 i didnt have this issue

**Comment by prithvi2226** [comment]
maybe can you share the block of the code in 'config.yaml' where you mentioned remote work, so that we can understand more of your problem? its surely some simple syntax issue

**Comment by azjz92** [comment]
remote: true

experienceLevel:
 internship: false
 entry: false
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: false
 week: false
 24 hours: true

positions:
  - software engineer
  - data scientist

locations:
  - London, United Kingdom
  - New York City

distance: 25

companyBlacklist:
  - Wayfair
  - Nuview

titleBlacklist:
  - mechanical engineer
  - test engineer

**Comment by azjz92** [comment]
[config.txt](https://github.com/user-attachments/files/16767840/config.txt)

**Comment by azjz92** [comment]
I was on windows, I reinstalled clean, and put my resume in the data folder, and created a venv then pip installed the requirements.txt , then i inserted the data folder example files into my normal data folder and tested with that and it worked, whatever combination of those things fixed the issue!
