### ISSUE TITLE
Bot fails to run when linkedin is already logged in.

### ISSUE THREAD

**Issue by sanjeethboddi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#94]
When I run `python main.py`, it fails to login as it can't find the login page as it's already logged in. 

```
Starting Chrome browser to log in to LinkedIn.
Navigating to the LinkedIn login page...
Login form not found. Aborting login.
Login button not found. Please verify the page structure.
```
quick fix: log off and remove account.

**Comment by feder-cr** [comment]
this is really strange, please more information

**Comment by bakissation** [comment]
Having same issue, i suggest launching a private navigation windows each time, but for 2FA users it will be too much, best solution is to check if logged in to the same account provided, if so proceed, else disconnect and remove account either by deleting session local storage or by web manipulation.

**Comment by fabiodeandrade** [comment]
a good solution here is caching your id session saved on your browser cookies after you logged in linkedin. The project uses selenium, so its easy to put before bot initialization

**Comment by sanjeethboddi** [comment]
The problem is due to the [change in linkedin post element's text](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/main/src/linkedIn_authenticator.py#L74C44-L74C56). 

Using text for checking is not a better approach. We have to use cssSelectors efficiently to find an element to check if we are logged in or not.

**Comment by feder-cr** [comment]
Ok, let me know any updates

**Comment by Antharithm** [comment]
Bot opens Chrome from a new window, in this new window I am signed OUT of linkedin - even though I am already signed in from the chrome browser

**Comment by rishabhrjain** [comment]
just comment out the login part and this problem can be solved. Although the code is not able to apply for jobs

<img width="430" alt="image" src="https://github.com/user-attachments/assets/ec78cc16-8fb4-4101-83fd-ee334c4cd0f3">

**Comment by acortiv** [comment]
The easiest fix for this is to just logout of LinkedIn after running the script and clear browser cache.
