### ISSUE TITLE
Support for other chromium based browsers.

### ISSUE THREAD

**Issue by sanjeethboddi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#95]
I'm using Arc as my default browser.

Even though after adding the executable path to the code, it still looks for Chrome binary executable. 
        `return webdriver.Chrome(service=service, options=options, executable_path="/Applications/Arc.app")`
        
        
quick fix: just install chrome.

**Comment by feder-cr** [comment]
Added to the things to do!
