### ISSUE TITLE
Huge delay in filling the forms

### ISSUE THREAD

**Issue by sanjeethboddi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#99]
It takes around 30 seconds to fill one single input field. Needed to be optimized.

**Comment by jvondermarck** [comment]
That's why, it will be probably handled in a better way in the future : https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/blob/08db7ca2157416a40ef5674464b068eec25c50d0/src/linkedIn_authenticator.py#L33
